import { LessonVideoStep } from './types';

// ==========================================
// 1. MOVE (移動) / SELECTING GEOMETRY VIDEO
// ==========================================
export const SELECTING_GEOMETRY_VIDEO_STEPS: LessonVideoStep[] = [
  {
    id: 'select-geo-step-0',
    title: '移動の概要',
    customText: '移動コマンドは、サイズや形状を変えずに、3Dオブジェクトの位置を変更するために使用します。',
    narrationText: '移動コマンドは、サイズや形状を変えずに、3Dオブジェクトの位置を変更するために使用します。',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 0.01,
    holdVideo: true,
    waitForNarrationBeforeVideo: true,
  },
  {
    id: 'select-geo-step-1',
    title: '1. 移動ツールの選択',
    customText: 'アイコンメニューから「移動」を選択します。',
    narrationText: 'アイコンメニューから移動を選択します。',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 2.5,
    overlays: [
      {
        id: 'highlight-move-group-jp',
        type: 'highlight',
        startTime: 0.3,
        endTime: 2.4,
        target: { x: 0.895, y: 0.355, width: 0.080, height: 0.025 },
        label: '移動・コピー・削除',
        labelPosition: 'left',
        animation: 'pulse',
      },
      {
        id: 'highlight-move-icon-jp',
        type: 'highlight',
        startTime: 0.8,
        endTime: 2.5,
        target: { x: 0.910, y: 0.380, width: 0.028, height: 0.042 },
        label: '移動',
        labelPosition: 'left',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'select-geo-step-2',
    title: '2. オブジェクトの選択',
    customText: '移動したいオブジェクトを左クリックします。',
    narrationText: '移動したいオブジェクトを左クリックします。',
    narrateTitle: false,
    videoStart: 2.5,
    videoEnd: 6.0,
    overlays: [
      {
        id: 'highlight-prompt-target-jp',
        type: 'highlight',
        startTime: 2.5,
        endTime: 6.0,
        target: { x: 0.005, y: 0.970, width: 0.220, height: 0.028 },
        label: 'プロンプト: 対象要素 GO',
        labelPosition: 'top',
        animation: 'pulse',
      },
      {
        id: 'highlight-box-selection-jp',
        type: 'highlight',
        startTime: 4.6,
        endTime: 6.0,
        target: { x: 0.28, y: 0.55, width: 0.28, height: 0.35 },
        label: 'オブジェクトの選択',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'select-geo-step-3',
    title: '3. 移動量の入力',
    customText: 'アイテム入力欄で各軸の移動量を入力し、Enterキーを押してオブジェクトを移動します。',
    narrationText: 'アイテム入力欄で移動量を入力し、Enterキーを押して移動を実行します。',
    narrateTitle: false,
    waitForNarrationBeforeVideo: true,
    videoStart: 6.0,
    videoEnd: 8.5,
    overlays: [
      {
        id: 'highlight-movement-entry-jp',
        type: 'highlight',
        startTime: 6.0,
        endTime: 8.5,
        target: { x: 0.055, y: 0.940, width: 0.220, height: 0.038 },
        label: '移動量 X 30.0',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'select-geo-step-4',
    title: '4. 確定と移動結果の確認',
    customText: '移動を確定し、選択したオブジェクトが指定位置に移動したことを確認します。',
    narrationText: '移動を確定し、選択したオブジェクトが指定位置に移動したことを確認します。',
    narrateTitle: false,
    videoStart: 8.5,
    videoEnd: 10.36,
  },
  {
    id: 'select-geo-quiz-1',
    title: '知識チェック: 移動の実行',
    customText: 'iCAD SXで移動量を入力した後、オブジェクトを移動するにはどうしますか？',
    videoStart: 10.36,
    videoEnd: 10.36,
    holdVideo: true,
    quizData: {
      question: 'iCAD SXで移動量を入力した後、オブジェクトを移動するにはどうしますか？',
      options: [
        {
          text: 'Enterキーを押して移動を実行する',
          isCorrect: true,
          feedback: '正解です！指定したX・Y・Z軸の移動量に従い、Enterキーを押して移動を実行します。',
        },
        {
          text: 'Escキーを押す',
          isCorrect: false,
          feedback: '不正解です。Escキーを押すと現在の操作がキャンセルされます。',
        },
        {
          text: '余白を右クリックする',
          isCorrect: false,
          feedback: '不正解です。右クリックはコンテキストメニューの呼び出しや原点表示等に使用されます。',
        },
      ],
    },
  },
  {
    id: 'select-geo-recap',
    title: '移動のまとめ',
    customText: '移動を選択 → オブジェクトを選択 → 移動量を入力 → 確定',
    videoStart: 10.36,
    videoEnd: 10.36,
    holdVideo: true,
    recapData: {
      title: '移動（オブジェクトの移動手順）',
      items: [
        'アイコンメニューから「移動」を選択',
        '移動したいオブジェクトを左クリック',
        'アイテム入力欄で移動量（X, Y, Z）を入力',
        'Enterキーを押して移動を実行',
      ],
    },
  },
];

export const MOVE_VIDEO_STEPS = SELECTING_GEOMETRY_VIDEO_STEPS;

// ==========================================
// 2. ROTATE (回転) VIDEO
// ==========================================
export const ROTATE_VIDEO_STEPS: LessonVideoStep[] = [
  {
    id: 'rotate-step-0',
    title: '回転の概要',
    customText: '回転コマンドは、3Dオブジェクトのサイズや形状を変えずに、選択した軸を中心に回転させるために使用します。',
    narrationText: '回転コマンドは、3Dオブジェクトのサイズや形状を変えずに、選択した軸を中心に回転させるために使用します。',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 0.01,
    holdVideo: true,
    waitForNarrationBeforeVideo: true,
  },
  {
    id: 'rotate-step-1',
    title: '1. 回転の選択',
    customText: '画面右側の操作メニュー「移動・コピー・削除」から「回転」アイコンを選択します。',
    narrationText: 'アイコンメニューから回転を選択します。',
    narrateTitle: false,
    videoStart: 0.3,
    videoEnd: 3.5,
    overlays: [
      {
        id: 'highlight-rotate-group-jp',
        type: 'highlight',
        startTime: 1,
        endTime: 2.8,
        target: { x: 0.91, y: 0.362, width: 0.07, height: 0.025 },
        label: '移動・コピー・削除',
        labelPosition: 'left',
        animation: 'pulse',
      },
      {
        id: 'highlight-rotate-icon-jp',
        type: 'highlight',
        startTime: 2.8,
        endTime: 10,
        target: { x: 0.91, y: 0.418, width: 0.0188, height: 0.032 },
        label: '回転',
        labelPosition: 'left',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'rotate-step-2',
    title: '2. オブジェクトの選択',
    customText: '回転させたいオブジェクトを左クリックし、「GO」をクリック（またはEnterキー）して選択を確定します。',
    narrationText: '回転させたいオブジェクトを左クリックし、選択を確定します。',
    narrateTitle: false,
    videoStart: 3.5,
    videoEnd: 5.7,
    overlays: [
      {
        id: 'highlight-prompt-target-jp',
        type: 'highlight',
        startTime: 3.5,
        endTime: 5.7,
        target: { x: 0.005, y: 0.970, width: 0.220, height: 0.028 },
        label: 'プロンプト: 対象要素 GO',
        labelPosition: 'top',
        animation: 'pulse',
      },
      {
        id: 'highlight-rotate-object-jp',
        type: 'highlight',
        startTime: 3.6,
        endTime: 5.7,
        target: { x: 0.430, y: 0.350, width: 0.260, height: 0.320 },
        label: '対象オブジェクト',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'rotate-step-3',
    title: '3. 回転軸の設定',
    customText: 'オブジェクトが回転する軸を定義するために、2点を指定します。',
    narrationText: 'オブジェクトが回転する軸を定義するために、2点を指定します。',
    narrateTitle: false,
    videoStart: 5.7,
    videoEnd: 9.5,
    overlays: [
      {
        id: 'highlight-axis-pt1-jp',
        type: 'highlight',
        startTime: 5.7,
        endTime: 7.5,
        target: { x: 0.425, y: 0.510, width: 0.035, height: 0.035 },
        label: '回転軸 始点',
        labelPosition: 'top',
        animation: 'pulse',
      },
      {
        id: 'highlight-axis-pt2-jp',
        type: 'highlight',
        startTime: 7.5,
        endTime: 9.5,
        target: { x: 0.555, y: 0.665, width: 0.035, height: 0.035 },
        label: '回転軸 ２点',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'rotate-quiz-1',
    title: '知識チェック: 回転軸の指定',
    customText: 'iCAD SXで3Dオブジェクトの回転軸を定義するには、何点を指定しますか？',
    videoStart: 9.5,
    videoEnd: 9.5,
    holdVideo: true,
    quizData: {
      question: 'iCAD SXで3Dオブジェクトの回転軸を定義するには、何点を指定しますか？',
      options: [
        {
          text: '2点を指定して軸を定義する',
          isCorrect: true,
          feedback: '正解です！2点を指定することで3D空間内の回転軸ベクトルを定義します。',
        },
        {
          text: '任意の面で3点を指定する',
          isCorrect: false,
          feedback: '不正解です。3点は平面（ミラー面など）の定義に使用され、回転軸は2点で定義します。',
        },
        {
          text: '原点の中心のみをクリックする',
          isCorrect: false,
          feedback: '不正解です。回転軸は任意の2点を指定して設定します。',
        },
      ],
    },
  },
  {
    id: 'rotate-step-4',
    title: '4. 回転角度の入力',
    customText: 'アイテム入力欄で希望する回転角度（例: 90°）を入力し、Enterキーを押して回転を完了します。',
    narrationText: 'アイテム入力欄で回転角度90度を入力し、Enterキーを押して回転を完了します。',
    narrateTitle: false,
    videoStart: 9.5,
    videoEnd: 12.9,
    overlays: [
      {
        id: 'highlight-angle-entry-jp',
        type: 'highlight',
        startTime: 9.5,
        endTime: 12.9,
        target: { x: 0.065, y: 0.950, width: 0.100, height: 0.035 },
        label: '回転角度: 90.0°',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'rotate-step-5',
    title: '5. 回転結果の確認',
    customText: 'オブジェクトがサイズや形状を変えることなく、指定した軸を中心に90度正確に回転します。',
    narrationText: 'オブジェクトがサイズや形状を変えることなく、指定した軸を中心に90度回転します。',
    narrateTitle: false,
    videoStart: 12.9,
    videoEnd: 16.31,
  },
  {
    id: 'rotate-recap',
    title: '回転のまとめ',
    customText: '回転を選択 → オブジェクトを選択 → 軸を設定 → 角度を入力 → 確定',
    videoStart: 16.31,
    videoEnd: 16.31,
    holdVideo: true,
    recapData: {
      title: '回転（オブジェクトの回転手順）',
      items: [
        'アイコンメニューから「回転」を選択',
        '回転するオブジェクトを左クリックしGOで確定',
        '2点を指定して回転軸を設定',
        'アイテム入力欄に希望の回転角度（例: 90°）を入力',
        'Enterキーを押して回転を完了',
      ],
    },
  },
];

// ==========================================
// 3. MIRROR (ミラー) VIDEO
// ==========================================
export const MIRROR_VIDEO_STEPS: LessonVideoStep[] = [
  {
    id: 'mirror-step-0',
    title: 'ミラーの概要',
    customText: 'ミラーコマンドは、選択した平面を基準にして3Dオブジェクトの対称コピーを作成するために使用します。',
    narrationText: 'ミラーコマンドは、選択した平面を基準にして3Dオブジェクトの対称コピーを作成するために使用します。',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 0.01,
    holdVideo: true,
    waitForNarrationBeforeVideo: true,
  },
  {
    id: 'mirror-step-1',
    title: '1. ミラーの選択',
    customText: '画面右側の操作メニュー「移動・コピー・削除」から「ミラー」アイコンを選択します。',
    narrationText: 'アイコンメニューからミラーを選択します。',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 5,
    overlays: [
      {
        id: 'highlight-mirror-group-jp',
        type: 'highlight',
        startTime: 0.3,
        endTime: 2.9,
        target: { x: 0.91, y: 0.362, width: 0.07, height: 0.025 },
        label: '移動・コピー・削除',
        labelPosition: 'left',
        animation: 'pulse',
      },
      {
        id: 'highlight-mirror-icon-jp',
        type: 'highlight',
        startTime: 4,
        endTime: 5,
        target: { x: 0.91, y: 0.418, width: 0.0188, height: 0.032 },
        label: 'ミラー',
        labelPosition: 'left',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'mirror-step-2',
    title: '2. オブジェクトの選択',
    customText: 'ミラーしたいオブジェクトを左クリックし、「GO」をクリック（またはEnterキー）して確定します。',
    narrationText: 'ミラーしたいオブジェクトを左クリックし、確定します。',
    narrateTitle: false,
    videoStart: 5.0,
    videoEnd: 6.5,
    overlays: [
      {
        id: 'highlight-prompt-target-jp',
        type: 'highlight',
        startTime: 5.0,
        endTime: 6.5,
        target: { x: 0.005, y: 0.970, width: 0.220, height: 0.028 },
        label: 'プロンプト: 対象要素 GO',
        labelPosition: 'top',
        animation: 'pulse',
      },
      {
        id: 'highlight-mirror-object-jp',
        type: 'highlight',
        startTime: 5.0,
        endTime: 6.5,
        target: { x: 0.427, y: 0.345, width: 0.270, height: 0.340 },
        label: '対象オブジェクト',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'mirror-step-3',
    title: '3. ミラー面の設定',
    customText: 'オブジェクトがミラーリングされる平面を定義するために3点を指定します（または面をクリックします）。',
    narrationText: 'オブジェクトがミラーリングされる平面を定義するために3点を指定するか、面をクリックします。',
    narrateTitle: false,
    videoStart: 6.5,
    videoEnd: 13.8,
    overlays: [
      {
        id: 'highlight-plane-pt1-jp',
        type: 'highlight',
        startTime: 6.5,
        endTime: 8.8,
        target: { x: 0.470, y: 0.560, width: 0.035, height: 0.035 },
        label: '平面定義点 1',
        labelPosition: 'top',
        animation: 'pulse',
      },
      {
        id: 'highlight-plane-pt2-jp',
        type: 'highlight',
        startTime: 8.8,
        endTime: 11.5,
        target: { x: 0.480, y: 0.620, width: 0.035, height: 0.035 },
        label: '平面定義点 2',
        labelPosition: 'top',
        animation: 'pulse',
      },
      {
        id: 'highlight-plane-pt3-jp',
        type: 'highlight',
        startTime: 11.5,
        endTime: 13.8,
        target: { x: 0.585, y: 0.525, width: 0.035, height: 0.035 },
        label: '平面定義点 3',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'mirror-quiz-1',
    title: '知識チェック: ミラー面の指定',
    customText: 'iCAD SXで3Dオブジェクトのミラー面を定義するにはどうしますか？',
    videoStart: 13.8,
    videoEnd: 13.8,
    holdVideo: true,
    quizData: {
      question: 'iCAD SXで3Dオブジェクトのミラー面を定義するにはどうしますか？',
      options: [
        {
          text: '3点を指定するか面をクリックする',
          isCorrect: true,
          feedback: '正解です！3点を指定するか面を選択することで、対称面が定義されます。',
        },
        {
          text: '1点のみを指定する',
          isCorrect: false,
          feedback: '不正解です。1点では位置しか決まらず、3D空間の平面を定義するには3点が必要です。',
        },
        {
          text: '回転角度の数値を入力する',
          isCorrect: false,
          feedback: '不正解です。角度入力は「回転」操作で使用され、ミラーでは平面を指定します。',
        },
      ],
    },
  },
  {
    id: 'mirror-step-4',
    title: '4. 確定と結果の確認',
    customText: '選択を確定して、反対側に対称なミラー結果を作成します。',
    narrationText: '選択を確定して、ミラー結果を作成します。',
    narrateTitle: false,
    videoStart: 13.8,
    videoEnd: 17.10,
    overlays: [
      {
        id: 'highlight-mirror-result-jp',
        type: 'highlight',
        startTime: 13.8,
        endTime: 17.10,
        target: { x: 0.430, y: 0.350, width: 0.320, height: 0.320 },
        label: '対称ミラー作成結果',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'mirror-recap',
    title: 'ミラーのまとめ',
    customText: 'ミラーを選択 → オブジェクトを選択 → ミラー面を選択 → 確定',
    videoStart: 17.10,
    videoEnd: 17.10,
    holdVideo: true,
    recapData: {
      title: 'ミラー（オブジェクトのミラー手順）',
      items: [
        'アイコンメニューから「ミラー」を選択',
        'ミラーしたいオブジェクトを左クリック',
        '3点を指定するか面をクリックしてミラー面を設定',
        '確定してミラー結果を作成',
      ],
    },
  },
];

// ==========================================
// 4. COPY (コピー) VIDEO
// ==========================================
export const COPY_VIDEO_STEPS: LessonVideoStep[] = [
  {
    id: 'copy-step-0',
    title: 'コピーの概要',
    customText: 'コピーコマンドは、元のオブジェクトを残したまま、3Dオブジェクトの複製を1つまたは複数作成するために使用します。',
    narrationText: 'コピーコマンドは、元のオブジェクトを残したまま、3Dオブジェクトの複製を1つまたは複数作成するために使用します。',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 0.01,
    holdVideo: true,
    waitForNarrationBeforeVideo: true,
  },
  {
    id: 'copy-step-1',
    title: '1. コピーの選択',
    customText: '画面右側の操作メニュー「移動・コピー・削除」から「複写」（コピー）アイコンを選択します。',
    narrationText: 'アイコンメニューからコピーを選択します。',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 3.0,
    overlays: [
      {
        id: 'highlight-copy-group-jp',
        type: 'highlight',
        startTime: 0.3,
        endTime: 2.9,
        target: { x: 0.895, y: 0.355, width: 0.080, height: 0.025 },
        label: '移動・コピー・削除',
        labelPosition: 'left',
        animation: 'pulse',
      },
      {
        id: 'highlight-copy-icon-jp',
        type: 'highlight',
        startTime: 0.8,
        endTime: 3.0,
        target: { x: 0.925, y: 0.380, width: 0.028, height: 0.042 },
        label: '複写（コピー）',
        labelPosition: 'left',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'copy-step-2',
    title: '2. オブジェクトの選択',
    customText: 'コピーしたいオブジェクトを左クリックし、「GO」をクリック（またはEnterキー）して選択を確定します。',
    narrationText: 'コピーしたいオブジェクトを左クリックします。',
    narrateTitle: false,
    videoStart: 3.0,
    videoEnd: 5.5,
    overlays: [
      {
        id: 'highlight-prompt-target-jp',
        type: 'highlight',
        startTime: 3.0,
        endTime: 5.5,
        target: { x: 0.005, y: 0.970, width: 0.220, height: 0.028 },
        label: 'プロンプト: 対象要素 GO',
        labelPosition: 'top',
        animation: 'pulse',
      },
      {
        id: 'highlight-copy-object-jp',
        type: 'highlight',
        startTime: 3.2,
        endTime: 5.5,
        target: { x: 0.430, y: 0.350, width: 0.260, height: 0.320 },
        label: 'コピー対象オブジェクト',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'copy-step-3',
    title: '3. コピー距離と個数の入力',
    customText: 'アイテム入力欄でX軸、Y軸、Z軸の移動距離を入力し、作成するコピー数を入力してEnterキーを押します。',
    narrationText: 'アイテム入力欄でX、Y、Z軸の移動距離とコピー数を入力し、確定します。',
    narrateTitle: false,
    videoStart: 5.5,
    videoEnd: 11.0,
    overlays: [
      {
        id: 'highlight-copy-entry-jp',
        type: 'highlight',
        startTime: 5.5,
        endTime: 11.0,
        target: { x: 0.005, y: 0.950, width: 0.350, height: 0.038 },
        label: '移動量・複写数入力',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'copy-quiz-1',
    title: '理解度チェック: コピーコマンド',
    customText: 'iCAD SXで「コピー」コマンドを実行した際、元のオブジェクトはどうなりますか？',
    videoStart: 11.0,
    videoEnd: 11.0,
    holdVideo: true,
    quizData: {
      question: 'iCAD SXで「コピー」コマンドを実行した際、元のオブジェクトはどうなりますか？',
      options: [
        {
          text: '元のオブジェクトはそのまま残り、指定距離に複製が作成される',
          isCorrect: true,
          feedback: '正解です！移動コマンドとは異なり、コピーは元のオブジェクトを残したまま指定位置に複製を作成します。',
        },
        {
          text: '元のオブジェクトは削除され、複製に置き換わる',
          isCorrect: false,
          feedback: '不正解です。元のオブジェクトは削除されず残ります。',
        },
        {
          text: '元のオブジェクトの形状やサイズが変更される',
          isCorrect: false,
          feedback: '不正解です。コピーはオブジェクトの寸法や形状を変更しません。',
        },
      ],
    },
  },
  {
    id: 'copy-step-4',
    title: '4. 複製の確認',
    customText: '元のオブジェクトを残したまま、指定した移動距離に複製が正確に配置されたことを確認します。',
    narrationText: '元のオブジェクトを残したまま、指定した距離に複製が作成されました。',
    narrateTitle: false,
    videoStart: 11.0,
    videoEnd: 15.38,
  },
  {
    id: 'copy-recap',
    title: 'コピーのまとめ',
    customText: 'コピーを選択 → オブジェクトを選択 → X, Y, Z移動量を入力 → コピー数を入力 → 確定',
    videoStart: 15.38,
    videoEnd: 15.38,
    holdVideo: true,
    recapData: {
      title: 'コピー（オブジェクトの複製手順）',
      items: [
        'アイコンメニューから「コピー」を選択',
        'コピーしたいオブジェクトを左クリック',
        'アイテム入力欄でX、Y、Z軸の移動距離を入力',
        '作成するコピー数を入力',
        'Enterキーを押してコマンドを完了',
      ],
    },
  },
];

// ==========================================
// 5. ROTATE COPY (回転複写) VIDEO
// ==========================================
export const ROTATE_COPY_VIDEO_STEPS: LessonVideoStep[] = [
  {
    id: 'rotate-copy-step-0',
    title: '回転複写の概要',
    customText: '回転複写コマンドは回転ツールと同様に機能しますが、元のオブジェクトを残したまま回転した複製を作成します。',
    narrationText: '回転複写コマンドは回転ツールと同様に機能しますが、元のオブジェクトを残したまま回転した複製を作成します。',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 0.01,
    holdVideo: true,
    waitForNarrationBeforeVideo: true,
  },
  {
    id: 'rotate-copy-step-1',
    title: '1. 回転複写の選択',
    customText: '画面右側の操作メニュー「移動・コピー・削除」から「回転複写」アイコンを選択します。',
    narrationText: 'アイコンメニューから回転複写を選択します。',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 6.5,
    overlays: [
      {
        id: 'highlight-rotate-copy-group-jp',
        type: 'highlight',
        startTime: 0,
        endTime: 4.8,
        target: { x: 0.91, y: 0.362, width: 0.07, height: 0.025 },
        label: '移動・コピー・削除',
        labelPosition: 'left',
        animation: 'pulse',
      },
      {
        id: 'highlight-rotate-copy-icon-jp',
        type: 'highlight',
        startTime: 4.8,
        endTime: 10,
        target: { x: 0.927, y: 0.418, width: 0.0188, height: 0.032 },
        label: '回転複写',
        labelPosition: 'bottom',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'rotate-copy-step-2',
    title: '2. オブジェクトの選択',
    customText: '複製して回転させたいオブジェクトを左クリックし、選択を確定します。',
    narrationText: '複製して回転させたいオブジェクトを左クリックします。',
    narrateTitle: false,
    videoStart: 6.5,
    videoEnd: 9.0,
    overlays: [
      {
        id: 'highlight-rotate-copy-object-jp',
        type: 'highlight',
        startTime: 6.8,
        endTime: 9.0,
        target: { x: 0.370, y: 0.500, width: 0.150, height: 0.150 },
        label: '回転複写するオブジェクト',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'rotate-copy-step-3',
    title: '3. 回転軸の設定',
    customText: '回転軸を定義するために2点を指定します。',
    narrationText: '回転軸を定義するために2点を指定します。',
    narrateTitle: false,
    videoStart: 9.0,
    videoEnd: 13.5,
    overlays: [
      {
        id: 'highlight-axis-pt1-jp',
        type: 'highlight',
        startTime: 9.0,
        endTime: 11.2,
        target: { x: 0.552, y: 0.459, width: 0.02, height: 0.029 },
        label: '回転軸点 1',
        labelPosition: 'top',
        animation: 'pulse',
      },
      {
        id: 'highlight-axis-pt2-jp',
        type: 'highlight',
        startTime: 11.2,
        endTime: 13.5,
        target: { x: 0.552, y: 0.673, width: 0.02, height: 0.029 },
        label: '回転軸点 2',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'rotate-copy-step-4',
    title: '4. 回転角度の入力',
    customText: 'アイテム入力欄で希望する角度（例: 90°）と個数を入力し、Enterキーを押して回転複製を作成します。',
    narrationText: 'アイテム入力欄で希望する角度を入力し、Enterキーを押して回転複製を作成します。',
    narrateTitle: false,
    videoStart: 13.5,
    videoEnd: 24,
    overlays: [
      {
        id: 'highlight-angle-count-entry-jp',
        type: 'highlight',
        startTime: 13.5,
        endTime: 24,
        target: { x: 0.07, y: 0.945, width: 0.159, height: 0.030 },
        label: '回転角度 (90°)・個数 (3)',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'rotate-copy-quiz-1',
    title: '理解度チェック: 回転複写',
    customText: 'iCAD SXの「回転複写」コマンドは通常の「回転」とどのように異なりますか？',
    videoStart: 24,
    videoEnd: 24,
    holdVideo: true,
    quizData: {
      question: 'iCAD SXの「回転複写」コマンドは通常の「回転」とどのように異なりますか？',
      options: [
        {
          text: '元のオブジェクトを残したまま、指定した角度に回転した複製を作成する',
          isCorrect: true,
          feedback: '正解です！回転複写は元のオブジェクトを保持しながら、指定角度に複製を配置します。',
        },
        {
          text: '元のオブジェクト自体の寸法や形状を恒久的に変更する',
          isCorrect: false,
          feedback: '不正解です。回転複写は寸法を変更せず同一の複製を作成します。',
        },
        {
          text: '回転後に元のオブジェクトを自動的に削除する',
          isCorrect: false,
          feedback: '不正解です。通常の回転が元オブジェクトを移動させるのに対し、回転複写は元オブジェクトを残します。',
        },
      ],
    },
  },
  {
    id: 'rotate-copy-step-5',
    title: '5. 複製の確認',
    customText: '元のオブジェクトを残したまま、指定軸の周囲に90°間隔で回転複製が正確に作成されたことを確認します。',
    narrationText: '元のオブジェクトを残したまま、指定した軸の周囲に回転複製が作成されました。',
    narrateTitle: false,
    videoStart: 24,
    videoEnd: 24.167,
    holdVideo: true,
  },
  {
    id: 'rotate-copy-recap',
    title: '回転複写のまとめ',
    customText: '回転複写を選択 → オブジェクトを選択 → 軸を設定 → 角度を入力 → 確定',
    videoStart: 24.167,
    videoEnd: 24.167,
    holdVideo: true,
    recapData: {
      title: '回転複写（オブジェクトの回転複製手順）',
      items: [
        'アイコンメニューから「回転複写」を選択',
        '複製して回転させたいオブジェクトを左クリック',
        '回転軸を定義するために2点を指定',
        'アイテム入力欄で希望する角度（例: 90°）を入力',
        'Enterキーを押して回転複製を作成',
      ],
    },
  },
];

// ==========================================
// 6. MIRROR COPY (ミラー複写) VIDEO
// ==========================================
export const MIRROR_COPY_VIDEO_STEPS: LessonVideoStep[] = [
  {
    id: 'mirror-copy-step-0',
    title: 'ミラー複写の概要',
    customText: 'ミラー複写コマンドはミラーツールと同様に機能しますが、元のオブジェクトを残したまま鏡像複製を作成するために使用します。',
    narrationText: 'ミラー複写コマンドはミラーツールと同様に機能しますが、元のオブジェクトを残したまま鏡像複製を作成するために使用します。',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 0.01,
    holdVideo: true,
    waitForNarrationBeforeVideo: true,
  },
  {
    id: 'mirror-copy-step-1',
    title: '1. ミラー複写の選択',
    customText: '画面右側の操作メニュー「移動・コピー・削除」から「ミラー複写」アイコンを選択します。',
    narrationText: 'アイコンメニューからミラー複写を選択します。',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 5.0,
    overlays: [
      {
        id: 'highlight-mirror-copy-group-jp',
        type: 'highlight',
        startTime: 0,
        endTime: 2.2,
        target: { x: 0.91, y: 0.362, width: 0.07, height: 0.025 },
        label: '移動・コピー・削除',
        labelPosition: 'left',
        animation: 'pulse',
      },
      {
        id: 'highlight-mirror-copy-icon-jp',
        type: 'highlight',
        startTime: 2.2,
        endTime: 5.0,
        target: { x: 0.962, y: 0.418, width: 0.0188, height: 0.032 },
        label: 'ミラー複写',
        labelPosition: 'bottom',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'mirror-copy-step-2',
    title: '2. オブジェクトの選択',
    customText: '複製してミラーしたいオブジェクトを左クリックし、「GO」をクリック（またはEnterキー）して選択を確定します。',
    narrationText: '複製してミラーしたいオブジェクトを左クリックします。',
    narrateTitle: false,
    videoStart: 5.0,
    videoEnd: 15.0,
    overlays: [
      {
        id: 'highlight-prompt-target-jp',
        type: 'highlight',
        startTime: 5.0,
        endTime: 15.0,
        target: { x: 0.005, y: 0.970, width: 0.220, height: 0.028 },
        label: 'プロンプト: 対象要素 GO',
        labelPosition: 'top',
        animation: 'pulse',
      },
      {
        id: 'highlight-mirror-copy-obj1-jp',
        type: 'highlight',
        startTime: 5.0,
        endTime: 15.0,
        target: { x: 0.305, y: 0.465, width: 0.095, height: 0.145 },
        label: '対象コンポーネント 1',
        labelPosition: 'top',
        animation: 'pulse',
      },
      {
        id: 'highlight-mirror-copy-obj2-jp',
        type: 'highlight',
        startTime: 8.0,
        endTime: 15.0,
        target: { x: 0.485, y: 0.270, width: 0.095, height: 0.170 },
        label: '対象コンポーネント 2',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'mirror-copy-step-3',
    title: '3. ミラー面の設定',
    customText: 'ミラー面を定義するために3点を指定します（または面を選択してミラー面として使用します）。',
    narrationText: 'ミラー面を定義するために3点を指定するか、面を選択します。',
    narrateTitle: false,
    videoStart: 15.0,
    videoEnd: 21.5,
    overlays: [
      {
        id: 'highlight-plane-pt1-jp',
        type: 'highlight',
        startTime: 15.0,
        endTime: 16.8,
        target: { x: 0.422, y: 0.597, width: 0.030, height: 0.040 },
        label: 'ミラー面指定点 1',
        labelPosition: 'top',
        animation: 'pulse',
      },
      {
        id: 'highlight-plane-pt2-jp',
        type: 'highlight',
        startTime: 16.8,
        endTime: 19.5,
        target: { x: 0.420, y: 0.690, width: 0.030, height: 0.040 },
        label: 'ミラー面指定点 2',
        labelPosition: 'bottom',
        animation: 'pulse',
      },
      {
        id: 'highlight-plane-pt3-jp',
        type: 'highlight',
        startTime: 19.5,
        endTime: 21.5,
        target: { x: 0.640, y: 0.380, width: 0.030, height: 0.040 },
        label: 'ミラー面指定点 3',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'mirror-copy-quiz-1',
    title: '理解度チェック: ミラー複写',
    customText: 'iCAD SXの「ミラー複写」コマンドは通常の「ミラー」とどのように異なりますか？',
    videoStart: 21.5,
    videoEnd: 21.5,
    holdVideo: true,
    quizData: {
      question: 'iCAD SXの「ミラー複写」コマンドは通常の「ミラー」とどのように異なりますか？',
      options: [
        {
          text: '元のオブジェクトを残したまま、鏡像の複製を作成する',
          isCorrect: true,
          feedback: '正解です！ミラー複写は元のオブジェクトを保持しながら、対称位置に鏡像の複製を作成します。',
        },
        {
          text: '元のオブジェクトを削除・移動し、元形状は残さない',
          isCorrect: false,
          feedback: '不正解です。通常のミラーは元オブジェクトを移動させますが、ミラー複写は元オブジェクトを残します。',
        },
        {
          text: 'オブジェクトの縮尺（スケール）を変更する',
          isCorrect: false,
          feedback: '不正解です。ミラー複写は縮尺を変更せず、同一形状の鏡像複製を作成します。',
        },
      ],
    },
  },
  {
    id: 'mirror-copy-step-4',
    title: '4. 確定と複製の確認',
    customText: '選択を確定し、元のオブジェクトを残したまま反対側に対称なミラー複製が作成されたことを確認します。',
    narrationText: '選択を確定し、反対側にミラー複製が作成されました。',
    narrateTitle: false,
    videoStart: 21.5,
    videoEnd: 25.517,
  },
  {
    id: 'mirror-copy-recap',
    title: 'ミラー複写のまとめ',
    customText: 'ミラー複写を選択 → オブジェクトを選択 → ミラー面を設定 → 確定',
    videoStart: 25.517,
    videoEnd: 25.517,
    holdVideo: true,
    recapData: {
      title: 'ミラー複写（オブジェクトの鏡像複製手順）',
      items: [
        'アイコンメニューから「ミラー複写」を選択',
        '複製してミラーしたいオブジェクトを左クリック',
        'ミラー面を定義するために3点を指定（または面を選択）',
        '選択を確定してミラー複製を作成',
      ],
    },
  },
];

// ==========================================
// 7. DELETE (削除) VIDEO
// ==========================================
export const DELETE_VIDEO_STEPS: LessonVideoStep[] = [
  {
    id: 'delete-step-0',
    title: '削除の概要',
    customText: '削除コマンドは、3Dモデルから不要なオブジェクトを取り除くために使用します。',
    narrationText: '削除コマンドは、3Dモデルから不要なオブジェクトを取り除くために使用します。',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 0.01,
    holdVideo: true,
    waitForNarrationBeforeVideo: true,
  },
  {
    id: 'delete-step-1',
    title: '1. 削除の選択',
    customText: '画面右側の操作メニュー「移動・コピー・削除」から「削除」アイコン（赤い×）を選択します。',
    narrationText: 'アイコンメニューから削除を選択します。',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 4.4,
    overlays: [
      {
        id: 'highlight-delete-group-jp',
        type: 'highlight',
        startTime: 0,
        endTime: 2.0,
        target: { x: 0.91, y: 0.362, width: 0.07, height: 0.025 },
        label: '移動・コピー・削除',
        labelPosition: 'left',
        animation: 'pulse',
      },
      {
        id: 'highlight-delete-icon-jp',
        type: 'highlight',
        startTime: 1.0,
        endTime: 4.4,
        target: { x: 0.962, y: 0.382, width: 0.021, height: 0.038 },
        label: '削除',
        labelPosition: 'left',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'delete-step-2',
    title: '2. オブジェクトの選択',
    customText: '3Dモデルから削除したいオブジェクトを左クリックします。',
    narrationText: '削除したいオブジェクトを左クリックします。',
    narrateTitle: false,
    videoStart: 4.4,
    videoEnd: 8.4,
    overlays: [
      {
        id: 'highlight-prompt-target-jp',
        type: 'highlight',
        startTime: 4.4,
        endTime: 8.4,
        target: { x: 0.005, y: 0.970, width: 0.220, height: 0.028 },
        label: 'プロンプト: 対象要素',
        labelPosition: 'top',
        animation: 'pulse',
      },
      {
        id: 'highlight-delete-object1-jp',
        type: 'highlight',
        startTime: 4.4,
        endTime: 6.3,
        target: { x: 0.310, y: 0.470, width: 0.355, height: 0.350 },
        label: '削除対象: フロント梁',
        labelPosition: 'top',
        animation: 'pulse',
      },
      {
        id: 'highlight-delete-object2-jp',
        type: 'highlight',
        startTime: 6.3,
        endTime: 8.4,
        target: { x: 0.576, y: 0.358, width: 0.184, height: 0.363 },
        label: '削除対象: 右側梁',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'delete-quiz-1',
    title: '知識チェック: 削除の確定',
    customText: 'iCAD SXでオブジェクトの削除を実行・確定するにはどうしますか？',
    videoStart: 8.4,
    videoEnd: 8.4,
    holdVideo: true,
    quizData: {
      question: 'iCAD SXでオブジェクトの削除を実行・確定するにはどうしますか？',
      options: [
        {
          text: '「GO」をクリックするかEnterキーを押して削除を確定する',
          isCorrect: true,
          feedback: '正解です！「GO」をクリックするかEnterキーを押すことで、選択したオブジェクトが削除されます。',
        },
        {
          text: 'Escキーを押す',
          isCorrect: false,
          feedback: '不正解です。Escキーを押すと削除操作がキャンセルされます。',
        },
        {
          text: '画面余白をダブルクリックする',
          isCorrect: false,
          feedback: '不正解です。余白クリックでは削除は確定されません。',
        },
      ],
    },
  },
  {
    id: 'delete-step-3',
    title: '3. 確定と削除結果の確認',
    customText: '選択を確定して、不要なオブジェクトが3Dモデルから削除されたことを確認します。',
    narrationText: '選択を確定してオブジェクトを削除します。',
    narrateTitle: false,
    videoStart: 8.4,
    videoEnd: 11.917,
    overlays: [
      {
        id: 'highlight-delete-prompt-go-jp',
        type: 'highlight',
        startTime: 8.4,
        endTime: 11.917,
        target: { x: 0.005, y: 0.970, width: 0.200, height: 0.028 },
        label: 'プロンプト: GOで削除確定',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'delete-recap',
    title: '削除のまとめ',
    customText: '削除を選択 → オブジェクトを選択 → 確定',
    videoStart: 11.917,
    videoEnd: 11.917,
    holdVideo: true,
    recapData: {
      title: '削除（オブジェクトの削除手順）',
      items: [
        'アイコンメニューから「削除」を選択',
        '削除したいオブジェクトを左クリック',
        '選択を確定してオブジェクトを削除',
      ],
    },
  },
];

export default SELECTING_GEOMETRY_VIDEO_STEPS;
