import { LessonVideoStep } from './types';

export const ORIGIN_AXES_VIDEO_STEPS: LessonVideoStep[] = [
  {
    id: 'origin-video-intro',
    title: '原点と座標軸のデモンストレーション',
    customText: '原点 (0, 0, 0) と X、Y、Z 軸が3D空間内で座標をどのように定義するか確認します。',
    videoStart: 0,
    videoEnd: 5,
  },
  {
    id: 'origin-video-inspect',
    title: '座標の向き',
    customText: '視図が回転する際、各軸がモデルの向きをどのように示しているかに注目してください。',
    videoStart: 5,
    videoEnd: 10,
    holdVideo: true,
  },
];

export const ORIGIN_LAYOUT_VIDEO_STEPS: LessonVideoStep[] = [
  {
    id: 'origin-layout-step-1',
    title: '1. パーツのレイアウトを変更する',
    customText: 'From the icon menu, navigate to パーツ (3D PARTS ) → パーツのレイアウトを変更する (Change 3D Part Layout).',
    narrationText: 'アイコンメニューから「パーツ」へ進み、「パーツのレイアウトを変更する」をクリックします。',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 5,
    overlays: [
      {
        id: 'highlight-vertical-tab-parts',
        type: 'highlight',
        startTime: 0.0,
        endTime: 2.5,
        target: { x: 0.979, y: 0.215, width: 0.02, height: 0.049 },
        label: 'パーツ (3D PARTS)',
        labelPosition: 'left',
        animation: 'pulse',
      },
      {
        id: 'highlight-header-parts',
        type: 'highlight',
        startTime: 2.5,
        endTime: 5.0,
        target: { x: 0.909, y: 0.119, width: 0.07, height: 0.03 },
        label: 'パーツ▼',
        labelPosition: 'left',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'origin-layout-step-2',
    title: '2. 現在の原点位置の表示',
    customText: '右クリックして、現在の原点位置を表示・確認します。',
    videoStart: 5,
    videoEnd: 9,
    overlays: [
      {
        id: 'highlight-icon-change-layout',
        type: 'highlight',
        startTime: 5.0,
        endTime: 9.0,
        target: { x: 0.959, y: 0.175, width: 0.022, height: 0.039 },
        label: 'パーツのレイアウトを変更する',
        labelPosition: 'left',
        animation: 'pulse',
      },
      {
        id: 'arrow-current-origin',
        type: 'arrow',
        startTime: 7.9,
        endTime: 9.0,
        line: {
          start: { x: 0.605, y: 0.765 },
          end: { x: 0.536, y: 0.655 },
          controlPoint: { x: 0.565, y: 0.74 },
        },
        label: '現在の原点位置',
        labelPosition: 'bottom',
        animation: 'pulse',
        narrate: false,
      },
    ],
  },
  {
    id: 'origin-layout-step-3',
    title: '3. 新しい原点位置の指定（点1）',
    customText: '新しく原点としたい位置（点1）を左クリックします。',
    videoStart: 9,
    videoEnd: 13.5,
    waitForNarrationBeforeVideo: true,
    overlays: [
      {
        id: 'highlight-point-1',
        type: 'highlight',
        startTime: 9.0,
        endTime: 13.5,
        target: { x: 0.4721, y: 0.692, width: 0.02, height: 0.03 },
        label: '点1：新原点',
        labelPosition: 'bottom',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'origin-layout-step-4',
    title: '4. X軸方向の指定（点2）',
    customText: '2点目を左クリックして、X軸の方向を設定します。',
    videoStart: 11,
    videoEnd: 15,
    overlays: [
      {
        id: 'highlight-point-2',
        type: 'highlight',
        startTime: 11.5,
        endTime: 15,
        target: { x: 0.628, y: 0.56, width: 0.02, height: 0.03 },
        label: '点2：X軸設定',
        labelPosition: 'bottom',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'origin-layout-step-5',
    title: '5. Y軸と正面図視図の設定（点3）',
    customText: '3点目を左クリックしてY軸を設定します。決定されたXY平面が正面図（Front View）になります。',
    videoStart: 15,
    videoEnd: 18,
    holdVideo: true,
    overlays: [
      {
        id: 'highlight-point-3',
        type: 'highlight',
        startTime: 15,
        endTime: 18,
        target: { x: 0.575, y: 0.33, width: 0.025, height: 0.035 },
        label: '点3：Y軸設定（正面図）',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'origin-layout-step-6',
    title: '6. 原点位置の変更完了',
    customText: '原点位置が変更されました。',
    narrationText: '原点位置が変更されました。',
    videoStart: 18,
    videoEnd: 20.83,
    holdVideo: true,
    overlays: [
      {
        id: 'highlight-origin-changed',
        type: 'highlight',
        startTime: 18,
        endTime: 20.83,
        target: { x: 0.503, y: 0.608, width: 0.044, height: 0.094 },
        label: '原点位置の変更完了',
        labelPosition: 'bottom',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'origin-layout-quiz-1',
    title: '理解度チェック',
    customText: '「パーツのレイアウトを変更する」を選択した後の最初の操作は何ですか？',
    videoStart: 20.83,
    videoEnd: 20.83,
    holdVideo: true,
    quizData: {
      question: '「パーツのレイアウトを変更する」を選択した後の最初の操作は何ですか？',
      options: [
        {
          text: '右クリックして現在の原点位置を表示・確認する',
          isCorrect: true,
          feedback: '正解です！右クリックで現在の原点位置を確認してから新しい原点を設定します。',
        },
        {
          text: 'すぐに左クリックして点1を指定する',
          isCorrect: false,
          feedback: '点1を指定する前に、まず右クリックで現在の原点位置を確認する必要があります。',
        },
        {
          text: 'キー入力領域に新しい座標数値を入力する',
          isCorrect: false,
          feedback: 'パーツ配置変更ツールではモデル上の点を指定するため、キー入力領域による直接入力ではありません。',
        },
      ],
    },
  },
  {
    id: 'origin-layout-quiz-2',
    title: '理解度チェック',
    customText: '3点指定による原点配置変更において、2点目（点2）は何を定義しますか？',
    videoStart: 20.83,
    videoEnd: 20.83,
    holdVideo: true,
    quizData: {
      question: '3点指定による原点配置変更において、2点目（点2）は何を定義しますか？',
      options: [
        {
          text: '新しい原点からのX軸のプラス方向',
          isCorrect: true,
          feedback: '正解です！点1が新原点、点2がX軸方向、点3がY軸方向（正面図）を定義します。',
        },
        {
          text: '垂直なZ軸の奥行き方向',
          isCorrect: false,
          feedback: '点2はX軸方向を設定するものであり、Z軸ではありません。',
        },
        {
          text: '作業平面の回転中心点',
          isCorrect: false,
          feedback: '点2は点1からのX軸のプラス方向を指定します。',
        },
      ],
    },
  },
  {
    id: 'origin-layout-quiz-3',
    title: '理解度チェック',
    customText: '3点目（点3：Y軸）を指定した後に確定される基準視図は何ですか？',
    videoStart: 20.83,
    videoEnd: 20.83,
    holdVideo: true,
    quizData: {
      question: '3点目（点3：Y軸）を指定した後に確定される基準視図は何ですか？',
      options: [
        {
          text: '正面図（XY平面）',
          isCorrect: true,
          feedback: '正解です！原点、X軸、Y軸によって形成されるXY平面がiCADの正面図（Front View）になります。',
        },
        {
          text: '上面図（XZ平面）',
          isCorrect: false,
          feedback: '点1・2・3によって決まるXY平面は正面図であり、上面図ではありません。',
        },
        {
          text: '側面図（YZ平面）',
          isCorrect: false,
          feedback: 'XY平面は正面図に対応しており、側面図ではありません。',
        },
      ],
    },
  },
  {
    id: 'origin-layout-recap',
    title: '3Dパーツ配置変更のまとめ',
    customText: '3Dパーツ配置変更レッスンで学んだ重要ポイントを振り返りましょう。',
    videoStart: 20.83,
    videoEnd: 20.83,
    holdVideo: true,
    recapData: {
      title: '3Dパーツ配置変更のまとめ',
      items: [
        'アイコンメニューから「パーツ (3D PARTS )」→「パーツのレイアウトを変更する」を選択します。',
        '右クリックでモデル上の現在の原点位置を表示・確認します。',
        '点1を左クリックして新しい原点位置を指定します。',
        '点2を左クリックしてX軸の方向を設定します。',
        '点3を左クリックしてY軸を設定し、正面図（XY平面）を確定します。',
      ],
    },
  },
];

export default ORIGIN_AXES_VIDEO_STEPS;
