import { LessonVideoStep } from './types';

export const SELECTING_GEOMETRY_VIDEO_STEPS: LessonVideoStep[] = [
  {
    id: 'select-geo-step-1',
    title: '1. 移動ツールの選択',
    customText: '画面右側の操作メニュー「移動・コピー・削除」から「移動」アイコンを選択します。',
    narrationText: '画面右側の操作メニュー「移動・コピー・削除」から「移動」アイコンを選択します。',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 3.2,
    overlays: [
      {
        id: 'highlight-move-group-jp',
        type: 'highlight',
        startTime: 0.5,
        endTime: 3.0,
        target: { x: 0.902, y: 0.250, width: 0.070, height: 0.025 },
        label: '移動・コピー・削除',
        labelPosition: 'left',
        animation: 'pulse',
      },
      {
        id: 'highlight-move-icon-jp',
        type: 'highlight',
        startTime: 1.0,
        endTime: 3.2,
        target: { x: 0.901, y: 0.264, width: 0.078, height: 0.069 },
        label: '移動',
        labelPosition: 'left',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'select-geo-step-2',
    title: '2. プロンプトとハイライトの確認',
    customText: '画面下のプロンプト「対象要素」を確認し、3D直方体にカーソルを重ねて黄色のハイライトを確認します。',
    narrationText: '画面下のプロンプト「対象要素」を確認し、3D直方体にカーソルを重ねて黄色のハイライトを確認します。',
    narrateTitle: false,
    videoStart: 3.2,
    videoEnd: 6.5,
    overlays: [
      {
        id: 'highlight-prompt-target-jp',
        type: 'highlight',
        startTime: 3.2,
        endTime: 6.5,
        target: { x: 0.005, y: 0.970, width: 0.250, height: 0.025 },
        label: 'プロンプト: 対象要素 GO',
        labelPosition: 'top',
        animation: 'pulse',
      },
      {
        id: 'highlight-box-selection-jp',
        type: 'highlight',
        startTime: 3.8,
        endTime: 6.5,
        target: { x: 0.395, y: 0.441, width: 0.205, height: 0.304 },
        label: '黄色のハイライト表示',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'select-geo-step-3',
    title: '3. 左クリックで選択しGOで確定',
    customText: 'ハイライトされた形状を左クリックして選択し、「GO」をクリックして選択を終了します。',
    narrationText: 'ハイライトされた形状を左クリックして選択し、「GO」をクリックして選択を終了します。',
    narrateTitle: false,
    videoStart: 6.5,
    videoEnd: 14.0,
    overlays: [
      {
        id: 'highlight-confirm-go-jp',
        type: 'highlight',
        startTime: 6.5,
        endTime: 10.0,
        target: { x: 0.005, y: 0.970, width: 0.250, height: 0.025 },
        label: 'GO（選択終了）',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'select-geo-quiz-1',
    title: '知識チェック: 図形要素の選択',
    customText: 'iCAD SXでクリックする前に対象形状を確認するにはどうしますか？',
    videoStart: 13.9,
    videoEnd: 13.9,
    holdVideo: true,
    quizData: {
      question: 'iCAD SXでクリックする前に対象形状を確認するにはどうしますか？',
      options: [
        {
          text: 'カーソルを重ねて黄色のハイライト表示を確認する',
          isCorrect: true,
          feedback: '正解です！黄色のハイライト表示により、クリックする前に対象形状を確実に確認できます。',
        },
        {
          text: 'オブジェクトを非表示にする',
          isCorrect: false,
          feedback: '不正解です。オブジェクトは画面に表示されたまま、黄色の輪郭線で強調表示されます。',
        },
        {
          text: '原点座標をリセットする',
          isCorrect: false,
          feedback: '不正解です。図形選択のホバー時に原点座標がリセットされることはありません。',
        },
      ],
    },
  },
  {
    id: 'select-geo-step-4',
    title: '4. 移動量の入力',
    customText: '画面下の入力欄に移動量（X, Y, Z）を入力し、Enterキーを押します。',
    narrationText: '画面下の入力欄に移動量（X, Y, Z）を入力し、Enterキーを押します。',
    narrateTitle: false,
    videoStart: 14.0,
    videoEnd: 24.0,
    overlays: [
      {
        id: 'highlight-movement-entry-jp',
        type: 'highlight',
        startTime: 14.0,
        endTime: 20.0,
        target: { x: 0.005, y: 0.940, width: 0.300, height: 0.035 },
        label: '移動量（X, Y, Z）',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'select-geo-step-5',
    title: '5. 移動結果の確認',
    customText: '選択したオブジェクトが指定位置へ移動し、未選択の要素はそのまま残ります。',
    narrationText: '選択したオブジェクトが指定位置へ移動し、未選択の要素はそのまま残ります。',
    narrateTitle: false,
    videoStart: 24.0,
    videoEnd: 36.78,
  },
  {
    id: 'select-geo-recap',
    title: '図形要素の選択のまとめ',
    customText: 'iCAD SXにおける図形要素の選択手順の重要ポイントを振り返ります。',
    videoStart: 36.78,
    videoEnd: 36.78,
    holdVideo: true,
    recapData: {
      title: '図形要素の選択のまとめ',
      items: [
        '操作メニューから機能（移動など）を選択',
        'プロンプト「対象要素」を確認',
        'カーソルを重ねて黄色のハイライトを確認',
        '左クリックで対象形状を選択',
        '「GO」をクリックして選択終了',
        '移動量を入力して実行',
      ],
    },
  },
];

export default SELECTING_GEOMETRY_VIDEO_STEPS;
