import { LessonVideoStep } from './types';

export const STANDARD_3D_VIEW_VIDEO_STEPS: LessonVideoStep[] = [
  {
    id: 'standard-view-introduction',
    title: '標準視図方向の選択',
    customText: '3D視図ツールバーを使用して、正面図、側面図、平面図、底面図などの正確な機械図面投影方向へ切り替えます。',
    videoStart: 0,
    videoEnd: 0.01,
    holdVideo: true,
  },
  {
    id: 'standard-view-demonstration',
    title: '標準視図の方向',
    customText: '選択された標準視図アイコンと、それに対応する視図方向の変化に注目してください。',
    videoStart: 0,
    videoEnd: 7,
    narrationEnabled: false,
    overlays: [
      {
        id: 'highlight-front-view',
        type: 'highlight',
        startTime: 0.85,
        endTime: 1.7,
        target: { x: 0.437, y: 0.038, width: 0.017, height: 0.03 },
        label: '正面',
        labelPosition: 'bottom',
        animation: 'pulse',
        centerCaption: true,
        captionPosition: { x: 0.545, y: 0.28 },
      },
      {
        id: 'highlight-top-view',
        type: 'highlight',
        startTime: 1.7,
        endTime: 3.7,
        target: { x: 0.424, y: 0.038, width: 0.017, height: 0.03 },
        label: '上面',
        labelPosition: 'bottom',
        animation: 'pulse',
        centerCaption: true,
        captionPosition: { x: 0.545, y: 0.28 },
      },
      {
        id: 'highlight-bottom-view',
        type: 'highlight',
        startTime: 3.7,
        endTime: 4.7,
        target: { x: 0.487, y: 0.038, width: 0.017, height: 0.03 },
        label: '下面',
        labelPosition: 'bottom',
        animation: 'pulse',
        centerCaption: true,
        captionPosition: { x: 0.545, y: 0.28 },
      },
      {
        id: 'highlight-right-view',
        type: 'highlight',
        startTime: 4.7,
        endTime: 5.7,
        target: { x: 0.45, y: 0.038, width: 0.016, height: 0.03 },
        label: '右側面',
        labelPosition: 'bottom',
        animation: 'pulse',
        centerCaption: true,
        captionPosition: { x: 0.545, y: 0.28 },
      },
      {
        id: 'highlight-left-view',
        type: 'highlight',
        startTime: 5.7,
        endTime: 7,
        target: { x: 0.463, y: 0.038, width: 0.016, height: 0.03 },
        label: '左側面',
        labelPosition: 'bottom',
        animation: 'pulse',
        centerCaption: true,
        captionPosition: { x: 0.545, y: 0.28 },
      },
    ],
  },
  {
    id: 'standard-view-inspection',
    title: '正投影による幾何検査',
    customText: '各標準視図は特定の軸に沿って直角に投影されるため、面、穴、エッジの整列状態を容易に検査できます。',
    videoStart: 7,
    videoEnd: 7.01,
    holdVideo: true,
  },
  {
    id: 'standard-view-quiz-1',
    title: '理解度チェック',
    customText: 'モデルを正面、側面、上面、下面の視図方向へ切り替える操作部はどれですか？',
    videoStart: 7,
    videoEnd: 7.01,
    holdVideo: true,
    quizData: {
      question: 'モデルを正面、側面、上面、下面の視図方向へ切り替える操作部はどれですか？',
      options: [
        { text: '3D視図ツールバー', isCorrect: true, feedback: '正解です！標準視図の方向は3D視図ツールバーから選択します。' },
        { text: '幾何作成ツールバー', isCorrect: false, feedback: 'これは幾何形状を作成するツールバーであり、視図方向は変更しません。' },
        { text: 'レイヤー表示リスト', isCorrect: false, feedback: 'レイヤー表示は要素の表示/非表示を制御するもので、視図方向ではありません。' },
      ],
    },
  },
  {
    id: 'standard-view-quiz-2',
    title: '理解度チェック',
    customText: 'モデルを検査する際に標準視図が有効な理由は何ですか？',
    videoStart: 7,
    videoEnd: 7.01,
    holdVideo: true,
    quizData: {
      question: 'モデルを検査する際に標準視図が有効な理由は何ですか？',
      options: [
        { text: 'モデルを正確な基準投影方向に正対させるため。', isCorrect: true, feedback: '正解です！遠近感の曖昧さなく面やフィーチャーを正確に比較できます。' },
        { text: '部品の立体幾何形状を恒久的に回転させるため。', isCorrect: false, feedback: '視図の変更によって部品自体の形状や座標が変わることはありません。' },
        { text: 'モデルの寸法を自動的に変更するため。', isCorrect: false, feedback: '視図方向を変更しても寸法値は変更されません。' },
      ],
    },
  },
  {
    id: 'standard-view-recap',
    title: '3D視図のまとめ',
    customText: '3D視図レッスンで学んだ重要ポイントを振り返りましょう。',
    videoStart: 7,
    videoEnd: 7.01,
    holdVideo: true,
    recapData: {
      title: '3D視図のまとめ',
      items: [
        '3D視図ツールバーから正面、側面、上面、下面を選択できます。',
        '標準視図は観察する視図方向のみを変更します。',
        '直角正投影の視図を活用して、面、穴、エッジを明瞭に検査します。',
      ],
    },
  },
];

export const USER_VIEW_VIDEO_STEPS: LessonVideoStep[] = [
  {
    id: 'isometric-multiple-faces',
    title: '複数面の同時立体表示',
    customText: '3D視図ツールバーからアイソメトリック視図を選択し、モデルの幅・高さ・奥行きを同時に確認します。',
    videoStart: 0,
    videoEnd: 6,
    overlays: [
      {
        id: 'highlight-isometric-view-toolbar',
        type: 'highlight',
        startTime: 0.2,
        endTime: 2.7,
        target: { x: 0.28, y: 0.01, width: 0.058, height: 0.031 },
        label: 'アイソメトリック視図を選択',
        labelPosition: 'bottom',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'isometric-overall-form',
    title: '立体全体の把握',
    customText: 'ユーザ視図を活用してモデル全体の立体形状を把握します。この操作でも部品幾何自体は移動しません。',
    videoStart: 6,
    videoEnd: 6.01,
    holdVideo: true,
  },
  {
    id: 'isometric-quiz-1',
    title: '理解度チェック',
    customText: 'ユーザ視図が最も明確に表現できるものは何ですか？',
    videoStart: 6,
    videoEnd: 6.01,
    holdVideo: true,
    quizData: {
      question: 'ユーザ視図が最も明確に表現できるものは何ですか？',
      options: [
        { text: 'モデルの複数の面を同時に立体視すること', isCorrect: true, feedback: '正解です！ユーザ視図により複数の面にわたる立体的な形状が把握できます。' },
        { text: '奥行きのない正面の1面のみ', isCorrect: false, feedback: 'それは正面直角図の特徴であり、ユーザ視図ではありません。' },
        { text: '隠れた作図補助線のみ', isCorrect: false, feedback: 'ユーザ視図は立体の向きを変えるもので、補助線のみを抽出する機能ではありません。' },
      ],
    },
  },
  {
    id: 'isometric-quiz-2',
    title: '理解度チェック',
    customText: '別のアイソメトリック視図方向を選択したとき、何が変化しますか？',
    videoStart: 6,
    videoEnd: 6.01,
    holdVideo: true,
    quizData: {
      question: '別のアイソメトリック視図方向を選択したとき、何が変化しますか？',
      options: [
        { text: '同じモデルに対するカメラの観察方向', isCorrect: true, feedback: '正解です！モデル形状はそのまま維持され、観察方向のみが変化します。' },
        { text: '部品に保存されている物理的な向き', isCorrect: false, feedback: '視図を変更しても部品自体の幾何配置は回転・変更されません。' },
        { text: '各フィーチャーに設定された寸法値', isCorrect: false, feedback: '視図を変更しても寸法値は一切変わりません。' },
      ],
    },
  },
  {
    id: 'isometric-recap',
    title: 'ユーザ視図のまとめ',
    customText: 'ユーザ視図レッスンで学んだ重要ポイントを振り返りましょう。',
    videoStart: 6,
    videoEnd: 6.01,
    holdVideo: true,
    recapData: {
      title: 'ユーザ視図のまとめ',
      items: [
        '3D視図ツールバーからアイソメトリック方向を選択します。',
        '複数の面と3次元すべての広がりを一度に立体的に観察できます。',
        '視図を切り替えても、部品の幾何形状や寸法が変化することはありません。',
      ],
    },
  },
];
