import React from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { invitationService, InvitationPreview } from '../../services/invitationService';
import './InvitationAcceptance.css';

export const InvitationAcceptanceView:React.FC=()=>{
  const [params]=useSearchParams(); const token=params.get('token')||'';
  const [preview,setPreview]=React.useState<InvitationPreview|null>(null); const [error,setError]=React.useState(''); const [message,setMessage]=React.useState(''); const [busy,setBusy]=React.useState(true);
  const [form,setForm]=React.useState({username:'',password:'',privacy_accepted:false,terms_accepted:false});
  React.useEffect(()=>{ if(!token){setError('Invitation link is missing.');setBusy(false);return;} invitationService.validate(token).then(setPreview).catch(()=>setError('This invitation is invalid, expired, cancelled, or already used.')).finally(()=>setBusy(false)); },[token]);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const result=await invitationService.accept({token,...form,privacy_policy_version:'2026-08',terms_version:'2026-08'});setMessage(result.message);}catch(err:any){setError(err?.response?.data?.detail||'Invitation could not be accepted.');}finally{setBusy(false);}};
  return <div className="invitation-page"><section className="invitation-card"><span>KMTI TRAINING HUB</span><h1>{message?'Invitation accepted':'Accept your invitation'}</h1>{busy&&!preview?<p>Checking invitation…</p>:error?<><p className="invitation-error">{error}</p><Link to="/login">Return to sign in</Link></>:message?<><p>{message}</p><Link className="invitation-primary" to="/login">Sign in</Link></>:preview&&<><div className="invitation-summary"><strong>{preview.full_name}</strong><small>{preview.email}</small><p>Role: {preview.role_code}{preview.plan_name?` · Plan: ${preview.plan_name}`:''}</p>{preview.admin_areas.length>0&&<p>Admin areas: {preview.admin_areas.join(', ')}</p>}</div><form onSubmit={submit}><label>Choose username<input required minLength={2} value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label>Create password<input required minLength={8} type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label className="invitation-check"><input type="checkbox" checked={form.privacy_accepted} onChange={e=>setForm({...form,privacy_accepted:e.target.checked})}/> I accept the privacy policy.</label><label className="invitation-check"><input type="checkbox" checked={form.terms_accepted} onChange={e=>setForm({...form,terms_accepted:e.target.checked})}/> I accept the terms of use.</label><button disabled={busy||!form.privacy_accepted||!form.terms_accepted}>{busy?'Accepting…':'Accept invitation'}</button></form></>}</section></div>;
};
