import sys
import os
import json

# Add the parent directory to sys.path to allow imports from backend
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from database import SessionLocal
from models import Quiz, Question

def sync_annotation_quiz():
    db = SessionLocal()
    try:
        # 1. New Question Data (as updated in mentorConstants.ts)
        new_questions = [
            {
                "text": "Identify the tool that allows a designer to generate length, width, height, and hole pitches for an entire part simultaneously without manual edge selection.",
                "options": ["Creates linear dimension", "Creates dimensions for 3D entities collectively", "Creates character strings", "Edits drafting entity characters"],
                "correct_answer": 1,
                "explanation": "The collective dimension tool automates the measurement of overall part bounds and internal features."
            },
            {
                "text": "What specific interface window is triggered when a user selects the tool to create a character string without a leader line?",
                "options": ["Dimension Property window", "Text Entry window", "Note String Entry window", "Edit Characters window"],
                "correct_answer": 1,
                "explanation": "Character strings (floating text) are defined within the Text Entry window."
            },
            {
                "text": "Which annotation feature requires the user to select exactly one edge of a circle to determine its size measurement?",
                "options": ["Linear dimension", "Diameter dimension", "Angular dimension", "Leader note"],
                "correct_answer": 1,
                "explanation": "A diameter dimension is generated by selecting the circular edge of a hole or cylinder."
            },
            {
                "text": "When utilizing the Notes with leader lines tool, what is the correct procedural order?",
                "options": ["Enter text > pick edge > click 3D space to position", "Pick edge > enter note in window > click 3D space to place", "Click 3D space > pick edge > edit dimension characters", "Select collective entity > enter note > press OK"],
                "correct_answer": 1,
                "explanation": "Leader notes require selecting the target geometry, entering the text, and then positioning the label."
            },
            {
                "text": "Which window provides granular control over visual elements like \"Arrow width,\" \"Arrow angle,\" and \"Dot diameter\"?",
                "options": ["Edit Dimension Characters", "Note String Entry", "Change Properties", "Text Entry"],
                "correct_answer": 2,
                "explanation": "The \"Change Properties\" (Attributes) menu allows for the customization of dimension and leader aesthetics."
            },
            {
                "text": "What is a primary functional difference between the \"Creates notes with leader lines\" tool and the \"Creates character strings\" tool?",
                "options": ["Leader lines can only be used on circular edges", "Character strings require the user to pick an edge first, while leader lines do not", "Leader lines connect text to a specific part feature, while character strings are placed freely in 3D space", "Character strings are for collective dimensions only"],
                "correct_answer": 2,
                "explanation": "Leaders are associative to geometry, whereas character strings are independent labels in the workspace."
            },
            {
                "text": "In the \"Edit Dimension Characters\" window, which option would a user toggle to control how numerical values are rounded or suppressed?",
                "options": ["Terminal Marks", "Zero suppress", "Arrow angle", "Font Stroke"],
                "correct_answer": 1,
                "explanation": "Zero suppression manages the display of leading or trailing zeros in dimension values."
            },
            {
                "text": "Scenario: A trainee is trying to measure the slope of a wedge-shaped part. They have selected the \"Angular dimension\" tool. Based on the 2-step process, what must they do immediately after selecting the two relevant edges?",
                "options": ["Pick an edge of the entity to show the note window", "Left-click on the 3D space to position the dimension", "Select \"GO\" from the collective dimension menu", "Change the line color to black in the properties window"],
                "correct_answer": 1,
                "explanation": "After defining the angle by selecting two edges, the final step is positioning the dimension in space."
            },
            {
                "text": "Scenario: You have generated several dimensions, but the text is too small to read and the arrows are overlapping. To fix the \"Height\" and \"Width ratio\" of the existing text, which specific icon sub-menu should you access?",
                "options": ["Creates linear dimension", "Edits drafting entity characters", "Changes the attributes of a drafting entity", "Changes the positions of drafting entities"],
                "correct_answer": 2,
                "explanation": "The \"Changes attributes\" (Properties) tool is used to modify the size and scale of existing drafting entities."
            },
            {
                "text": "Scenario: You are tasked with labeling a part as \"Part A\" in the workspace. This label does not need to point to any specific edge or surface. According to the lesson, which tool is most appropriate for this task?",
                "options": ["Creates notes with leader lines", "Creates character strings", "Creates diameter dimension", "Creates linear dimension"],
                "correct_answer": 1,
                "explanation": "Character strings are used for general labels and notes that do not require a leader arrow."
            }
        ]

        # 2. Find the Quiz
        quiz = db.query(Quiz).filter(Quiz.slug == 'annotation').first()
        if not quiz:
            print("Quiz 'annotation' not found in database. Creating it...")
            quiz = Quiz(
                slug='annotation',
                title='3D Annotation & MBD Principles',
                description='Understanding technical labeling and Product Manufacturing Information (PMI).',
                course_type='3D_Modeling'
            )
            db.add(quiz)
            db.flush()

        # 3. Update Questions
        existing_questions = db.query(Question).filter(Question.quiz_id == quiz.id).order_by(Question.order).all()
        
        for i, q_data in enumerate(new_questions):
            options_json = json.dumps(q_data['options'])
            if i < len(existing_questions):
                # Update existing
                q = existing_questions[i]
                q.text = q_data['text']
                q.options_json = options_json
                q.correct_answer = q_data['correct_answer']
                q.explanation = q_data['explanation']
                print(f"Updated question {i+1}")
            else:
                # Add new
                q = Question(
                    quiz_id=quiz.id,
                    text=q_data['text'],
                    options_json=options_json,
                    correct_answer=q_data['correct_answer'],
                    explanation=q_data['explanation'],
                    order=i
                )
                db.add(q)
                print(f"Added question {i+1}")

        # Delete extra questions if any
        if len(existing_questions) > len(new_questions):
            for j in range(len(new_questions), len(existing_questions)):
                db.delete(existing_questions[j])
                print(f"Deleted extra question {j+1}")

        db.commit()
        print("Successfully synced 'annotation' quiz questions to database.")

    except Exception as e:
        print(f"Error syncing quiz: {e}")
        db.rollback()
    finally:
        db.close()

if __name__ == "__main__":
    sync_annotation_quiz()
