import sys
import os
import json

# Add the parent directory to sys.path to allow imports from backend
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from database import SessionLocal
from models import Quiz, Question

def sync_interference_quiz():
    db = SessionLocal()
    try:
        # 1. New Question Data (as updated in mentorConstants.ts)
        new_questions = [
            {
                "text": "Identify the specific visual state that parts with detected interferences switch to so that the problematic areas become visible.",
                "options": ["Shaded view", "Transparent view", "Wireframe", "Hidden line view"],
                "correct_answer": 2,
                "explanation": "The viewport automatically switches to Wireframe mode during clash analysis to reveal internal overlaps."
            },
            {
                "text": "When an interference is identified, what specific geometric form and color does the system generate to highlight the overlapping area?",
                "options": ["Blue surface", "Red CGS Solid", "Green wireframe", "Yellow dot"],
                "correct_answer": 1,
                "explanation": "iCAD generates temporary Red CGS Solids to represent the physical volume of the interference."
            },
            {
                "text": "Name the specific menu action required to ensure the software performs a thorough and precise examination of all potential overlaps rather than a generalized scan.",
                "options": ["Select High-speed detection", "Right-click workspace", "Unselect High-speed detection", "Press Muhenkan + W"],
                "correct_answer": 2,
                "explanation": "Disabling \"High-speed detection\" performs a more rigorous volumetric analysis of the model."
            },
            {
                "text": "What is the primary purpose of utilizing the \"List Display\" tool after an interference check has been completed?",
                "options": ["To automatically delete all overlapping parts", "To view a window showing the specific names of 3D parts that are clashing with one another", "To change the color of the entire drawing to red", "To convert the 3D model into a 2D drafting entity"],
                "correct_answer": 1,
                "explanation": "The List Display window provides a detailed breakdown of which parts are involved in each detected clash."
            },
            {
                "text": "How can a user quickly check the \"entire drawing\" for overlaps without selecting every individual part manually?",
                "options": ["Double-click the Interference Check icon", "Use the Ctrl+Z keyboard shortcut", "Right-click on the 3D Space", "Select \"High-speed detection\" from the icon menu"],
                "correct_answer": 2,
                "explanation": "Right-clicking in the 3D space selects all visible entities for a global interference analysis."
            },
            {
                "text": "According to the lesson, what is the recommended method for removing the temporary red solids generated by the check once the analysis is finished?",
                "options": ["Use the \"Delete Component\" tool", "Unselect the parts in the List Display", "Use the Undo command or Ctrl+Z", "Toggle the work plane using Muhenkan+W"],
                "correct_answer": 2,
                "explanation": "The Undo command (Ctrl+Z) is the standard way to clear the interference analysis results and return to normal modeling."
            },
            {
                "text": "Within the List Display window, what happens when a user gets a specific 3D part name?",
                "options": ["The part is renamed automatically", "The system automatically zooms to and shows the specific interference area", "The part is moved to Layer 1", "A green hatch pattern is applied to the part's face"],
                "correct_answer": 1,
                "explanation": "Clicking an entry in the clash list focuses the camera on the specific location of that interference."
            },
            {
                "text": "Scenario: You are performing an interference check on a dense assembly. You select the tool and click GO, but the system reports \"0 locations detected\" despite you seeing parts visibly touching. Which step from the instructional guide likely needs to be adjusted to find the missing overlaps?",
                "options": ["You must switch the view to \"Top View\" first", "You need to unselect \"High-speed detection\" to check all interferences precisely", "You must paint the clashing parts green before checking", "You should use the \"Clearance Check\" tool instead"],
                "correct_answer": 1,
                "explanation": "High-speed detection might miss subtle contacts; a precise check requires unselecting that option."
            },
            {
                "text": "Scenario: After running a check, a dialog box appears stating \"2 locations detected.\" You see red shapes appearing inside your model. What is the next logical step an expert designer should take according to the 4-step workflow?",
                "options": ["Immediately save the file and close ICAD", "Analyze possible countermeasures to eliminate the physical overlap between the parts", "Select \"Separate Entity\" to detach the red solids", "Use \"Show/Hide Drafting Entity\" to remove the wireframe view"],
                "correct_answer": 1,
                "explanation": "The goal of the check is to identify and then physically resolve the geometric errors through redesign."
            },
            {
                "text": "Scenario: You are using the List Display window to manage multiple clashing parts. You want to focus on a specific clash between a \"Bracket\" and a \"Slide-plate.\" In the List Display interface, which columns contain the information needed to identify these specific clashing pairs?",
                "options": ["SPGR and Color Code", "3D Part Name 1 and 3D Part Name 2", "Target Entity and Tool Entity", "X-axis and Y-axis coordinates"],
                "correct_answer": 1,
                "explanation": "The list display explicitly names both parts involved in a clash in the \"3D Part Name\" columns."
            }
        ]

        # 2. Find the Quiz
        quiz = db.query(Quiz).filter(Quiz.slug == 'interference').first()
        if not quiz:
            print("Quiz 'interference' not found in database. Creating it...")
            quiz = Quiz(
                slug='interference',
                title='Advanced Clash Detection & Logic',
                description='Ensuring physical assembly feasibility through volumetric analysis.',
                course_type='3D_Modeling'
            )
            db.add(quiz)
            db.flush()

        # 3. Update Questions
        existing_questions = db.query(Question).filter(Question.quiz_id == quiz.id).order_by(Question.order).all()
        
        for i, q_data in enumerate(new_questions):
            options_json = json.dumps(q_data['options'])
            if i < len(existing_questions):
                # Update existing
                q = existing_questions[i]
                q.text = q_data['text']
                q.options_json = options_json
                q.correct_answer = q_data['correct_answer']
                q.explanation = q_data['explanation']
                print(f"Updated question {i+1}")
            else:
                # Add new
                q = Question(
                    quiz_id=quiz.id,
                    text=q_data['text'],
                    options_json=options_json,
                    correct_answer=q_data['correct_answer'],
                    explanation=q_data['explanation'],
                    order=i
                )
                db.add(q)
                print(f"Added question {i+1}")

        # Delete extra questions if any
        if len(existing_questions) > len(new_questions):
            for j in range(len(new_questions), len(existing_questions)):
                db.delete(existing_questions[j])
                print(f"Deleted extra question {j+1}")

        db.commit()
        print("Successfully synced 'interference' quiz questions to database.")

    except Exception as e:
        print(f"Error syncing quiz: {e}")
        db.rollback()
    finally:
        db.close()

if __name__ == "__main__":
    sync_interference_quiz()
