import { LessonVideoStep } from './types';

export const STANDARD_3D_VIEW_VIDEO_STEPS: LessonVideoStep[] = [
  {
    id: 'standard-view-introduction',
    title: 'Choose a standard direction',
    customText: 'Use the 3D View toolbar to switch to an exact engineering direction, such as front, side, top, or bottom.',
    videoStart: 0,
    videoEnd: 0.01,
    holdVideo: true,
  },
  {
    id: 'standard-view-demonstration',
    title: 'Standard view directions',
    customText: 'Watch the selected standard view icons and the matching view direction.',
    videoStart: 0,
    videoEnd: 7,
    narrationEnabled: false,
    overlays: [
      {
        id: 'highlight-front-view',
        type: 'highlight',
        startTime: 0.85,
        endTime: 1.7,
        target: { x: 0.437, y: 0.038, width: 0.017, height: 0.03 },
        label: 'FRONT',
        labelPosition: 'bottom',
        animation: 'pulse',
        centerCaption: true,
        captionPosition: { x: 0.545, y: 0.28 },
      },
      {
        id: 'highlight-top-view',
        type: 'highlight',
        startTime: 1.7,
        endTime: 3.7,
        target: { x: 0.424, y: 0.038, width: 0.017, height: 0.03 },
        label: 'TOP',
        labelPosition: 'bottom',
        animation: 'pulse',
        centerCaption: true,
        captionPosition: { x: 0.545, y: 0.28 },
      },
      {
        id: 'highlight-bottom-view',
        type: 'highlight',
        startTime: 3.7,
        endTime: 4.7,
        target: { x: 0.487, y: 0.038, width: 0.017, height: 0.03 },
        label: 'BOTTOM',
        labelPosition: 'bottom',
        animation: 'pulse',
        centerCaption: true,
        captionPosition: { x: 0.545, y: 0.28 },
      },
      {
        id: 'highlight-right-view',
        type: 'highlight',
        startTime: 4.7,
        endTime: 5.7,
        target: { x: 0.45, y: 0.038, width: 0.016, height: 0.03 },
        label: 'RIGHT',
        labelPosition: 'bottom',
        animation: 'pulse',
        centerCaption: true,
        captionPosition: { x: 0.545, y: 0.28 },
      },
      {
        id: 'highlight-left-view',
        type: 'highlight',
        startTime: 5.7,
        endTime: 7,
        target: { x: 0.463, y: 0.038, width: 0.016, height: 0.03 },
        label: 'LEFT',
        labelPosition: 'bottom',
        animation: 'pulse',
        centerCaption: true,
        captionPosition: { x: 0.545, y: 0.28 },
      },
    ],
  },
  {
    id: 'standard-view-inspection',
    title: 'Inspect aligned geometry',
    customText: 'Each standard view looks straight along one direction, making aligned faces, holes, and edges easier to inspect.',
    videoStart: 7,
    videoEnd: 7.01,
    holdVideo: true,
  },
];

export const USER_VIEW_VIDEO_STEPS: LessonVideoStep[] = [
  {
    id: 'isometric-multiple-faces',
    title: 'Display multiple faces',
    customText: 'Select an isometric direction from the 3D View toolbar to see the model width, height, and depth together.',
    videoStart: 0,
    videoEnd: 6,
    overlays: [
      {
        id: 'highlight-isometric-view-toolbar',
        type: 'highlight',
        startTime: 0.2,
        endTime: 2.7,
        target: { x: 0.28, y: 0.01, width: 0.058, height: 0.031 },
        label: 'Select an isometric direction',
        labelPosition: 'bottom',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'isometric-overall-form',
    title: 'Inspect the overall form',
    customText: 'Use User Views to understand the overall shape, while remembering that the component geometry itself does not move.',
    videoStart: 6,
    videoEnd: 6.01,
    holdVideo: true,
  },
];
