import { CalendarDays, Loader2, Plus, Users } from 'lucide-react';
import React from 'react';
import { adminService, Cohort, CourseRun, CurriculumCourse } from '../../../services/adminService';
import { authService, User } from '../../../services/authService';
import './CourseDeliveryManagement.css';

export const CourseDeliveryManagement:React.FC=()=>{
 const [cohorts,setCohorts]=React.useState<Cohort[]>([]),[runs,setRuns]=React.useState<CourseRun[]>([]),[courses,setCourses]=React.useState<CurriculumCourse[]>([]),[users,setUsers]=React.useState<User[]>([]);
 const [busy,setBusy]=React.useState(false),[error,setError]=React.useState(''),[reason,setReason]=React.useState('');
 const [learnerByRun,setLearnerByRun]=React.useState<Record<number,string>>({});
 const [cohort,setCohort]=React.useState({code:'',name:''});const [run,setRun]=React.useState({title:'',course_id:'',cohort_id:'',starts_at:'',instructor_user_id:''});
 const load=React.useCallback(async()=>{try{const [c,r,all,u]=await Promise.all([adminService.getCohorts(),adminService.getCourseRuns(),adminService.getCurriculumCourses(),authService.getUsers()]);setCohorts(c);setRuns(r);setCourses(all.filter(x=>x.lifecycle_status==='published'));setUsers(u);}catch{setError('Unable to load course delivery.');}},[]);React.useEffect(()=>{load()},[load]);
 const createCohort=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await adminService.createCohort(cohort);setCohort({code:'',name:''});await load()}catch(err:any){setError(err?.response?.data?.detail||'Cohort could not be created.')}finally{setBusy(false)}};
 const createRun=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await adminService.createCourseRun({title:run.title,course_id:+run.course_id,cohort_id:+run.cohort_id,starts_at:new Date(run.starts_at).toISOString(),instructor_user_id:run.instructor_user_id?+run.instructor_user_id:undefined});setRun({title:'',course_id:'',cohort_id:'',starts_at:'',instructor_user_id:''});await load()}catch(err:any){setError(err?.response?.data?.detail||'Course run could not be created.')}finally{setBusy(false)}};
 const enroll=async(runId:number)=>{const id=learnerByRun[runId];if(!id||reason.trim().length<3){setError('Select a learner and enter an enrollment reason.');return}setBusy(true);try{await adminService.enrollLearner(runId,+id,reason);setReason('');setLearnerByRun({...learnerByRun,[runId]:''});await load()}catch(err:any){setError(err?.response?.data?.detail||'Learner could not be enrolled.')}finally{setBusy(false)}};
 const instructors=users.filter(u=>u.role==='employee'), learners=users.filter(u=>u.role==='trainee');
 return <section className="delivery"><header><div><span>COURSE DELIVERY</span><h2>Cohorts and instructors</h2><p>Schedule published courses, assign instructors, and enroll learners.</p></div><strong>{runs.length} runs</strong></header>{error&&<div className="delivery-error">{error}</div>}
 <div className="delivery-forms"><form onSubmit={createCohort}><h3><Users size={16}/>New cohort</h3><input required placeholder="Cohort name" value={cohort.name} onChange={e=>setCohort({...cohort,name:e.target.value})}/><input required pattern="[A-Za-z0-9_-]+" placeholder="Cohort code" value={cohort.code} onChange={e=>setCohort({...cohort,code:e.target.value})}/><button disabled={busy}><Plus size={15}/>Create cohort</button></form><form onSubmit={createRun}><h3><CalendarDays size={16}/>Schedule course run</h3><input required placeholder="Run title" value={run.title} onChange={e=>setRun({...run,title:e.target.value})}/><select required value={run.course_id} onChange={e=>setRun({...run,course_id:e.target.value})}><option value="">Published course</option>{courses.map(x=><option value={x.id} key={x.id}>{x.title}</option>)}</select><select required value={run.cohort_id} onChange={e=>setRun({...run,cohort_id:e.target.value})}><option value="">Cohort</option>{cohorts.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><select value={run.instructor_user_id} onChange={e=>setRun({...run,instructor_user_id:e.target.value})}><option value="">Assign later</option>{instructors.map(x=><option value={x.id} key={x.id}>{x.full_name}</option>)}</select><input required type="datetime-local" value={run.starts_at} onChange={e=>setRun({...run,starts_at:e.target.value})}/><button disabled={busy}>{busy?<Loader2 className="spin" size={15}/>:<Plus size={15}/>}Schedule run</button></form></div>
 <div className="delivery-reason"><label>Reason for enrollment</label><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Required for audit records"/><small>{learners.length} learners available</small></div><div className="delivery-runs">{runs.map(x=><article key={x.id}><span>{x.status}</span><h3>{x.title}</h3><p>{x.course_title} · {x.cohort_name}</p><small>{new Date(x.starts_at).toLocaleString()} · Instructor: {x.instructor_name||'Unassigned'} · {x.enrollment_count} enrolled</small><select value={learnerByRun[x.id]||''} onChange={e=>setLearnerByRun({...learnerByRun,[x.id]:e.target.value})}><option value="">Select learner</option>{learners.map(user=><option key={user.id} value={user.id}>{user.full_name}</option>)}</select><button onClick={()=>enroll(x.id)} disabled={busy}>Enroll learner</button></article>)}</div></section>
}
