import { cleanup, render, screen } from '@testing-library/react';
import { afterEach, expect, it } from 'vitest';
import FoundationStretchSteps from '../FoundationStretchSteps';
import FoundationViewComparison from '../FoundationViewComparison';
import ComponentRotateCopyArtwork, { componentRotateComparisonIcons } from '../ComponentRotateCopyArtwork';
import { resolveFoundationLesson } from '../curriculum';
import { foundationKnowledgeQuestions } from '../knowledgeCheck';
afterEach(cleanup);
it.each(['en','ja'] as const)('renders Rotate Copy points, result distinction, comparison, and quiz in %s', language => {
 const lesson=resolveFoundationLesson('foundation-component-rotate-copy')!;
 const sections=lesson.content[language].sections!;
 const {container}=render(<><FoundationStretchSteps text={sections[0].text} method={1} japanese={language==='ja'} customIcons={[0,1,2,3,4].map(step=><ComponentRotateCopyArtwork key={step} step={step} japanese={language==='ja'}/>)}/><FoundationViewComparison text={sections[1].text} customIcons={componentRotateComparisonIcons()}/></>);
 const cards=screen.getAllByRole('listitem');
 expect(cards).toHaveLength(5);
 expect(screen.getAllByRole('button')).toHaveLength(5);
 expect(cards[2]).toHaveTextContent('P1');
 expect(cards[2]).toHaveTextContent('P2');
 expect(cards[3]).toHaveTextContent('回転角度');
 expect(cards[4]).toHaveTextContent(language==='ja'?'元の構成要素は元の位置に残ります。':'The original remains in place.');
 expect(container.querySelectorAll('.foundation-view-comparison__card')).toHaveLength(2);
 const question=foundationKnowledgeQuestions(language,lesson.id)[0];
 expect(question.id).toBe('foundation-component-rotate-copy-knowledge-check');
 expect(question.choices.filter(choice=>choice.isCorrect).map(choice=>choice.label)).toEqual([language==='ja'?'B. 回転コピーは回転した複製を作成する':'B. Rotate Copy Component creates a rotated duplicate']);
});
