import {cleanup,render,screen} from '@testing-library/react';
import {afterEach,expect,it} from 'vitest';
import LayerDesignationContent from '../LayerDesignationContent';
import {resolveFoundationLesson,foundationNeighbors} from '../curriculum';
import {foundationKnowledgeQuestions} from '../knowledgeCheck';
afterEach(cleanup);
it.each(['en','ja'] as const)('renders five categories and exact reference tables in %s',lang=>{
 const lesson=resolveFoundationLesson('F23.3')!;
 const sections=lesson.content[lang].sections!;
 const {container}=render(<>{sections.map((s,index)=><LayerDesignationContent key={index} {...s} index={index} japanese={lang==='ja'}/>)}</>);
 expect(container.querySelectorAll('.foundation-view-comparison__card')).toHaveLength(5);
 expect(container.querySelector('.layer-designation__card--layer3')).toBeTruthy();
 const headings=screen.getAllByRole('heading').map(h=>h.textContent);
 [1,1,2,2,3].forEach((layer,i)=>expect(headings[i]).toContain(`${lang==='ja'?'レイヤ':'Layer'} ${layer}`));
 expect(screen.getAllByRole('table')).toHaveLength(4);
 expect(container.querySelector('.layer-designation__table--quick-reference')).toBeTruthy();
 expect(container.querySelector('.foundations-uses__grid')).toBeNull();
 expect(screen.getByRole('row',{name:'Urethane No. 18'})).toBeTruthy();
 const heat=screen.getAllByRole('table')[2];
 expect(heat.textContent).toContain('No. 1');
 expect(heat.textContent).toContain('No. 16');
 expect(screen.getByRole('img',{name:lang==='ja'?'材質リストの色番号':'Material List Color Codes'})).toBeTruthy();
 expect(heat.textContent).toContain('Isonite, Ionite, Parsonite');
 expect(heat.textContent).toContain('Parkerizing, Manganese Phosphate');
 const q=foundationKnowledgeQuestions(lang,lesson.id)[0];
 expect(q.id).toBe('foundation-properties-part-layer-designation-knowledge-check');
 expect(q.choices.map(c=>c.isCorrect)).toEqual([false,false,true,false]);
 expect(foundationNeighbors(lesson.id)).toEqual({previous:'foundation-properties-change-layer',next:'F17.1'});
 expect(resolveFoundationLesson('F24.1')?.title.en).toBe('Foundation Review');
});
