import { LessonVideoStep } from './types';

// ==========================================
// 1. MOVE (移動) / SELECTING GEOMETRY VIDEO
// ==========================================
export const SELECTING_GEOMETRY_VIDEO_STEPS: LessonVideoStep[] = [
  {
    id: 'select-geo-step-0',
    title: 'Move Introduction',
    customText: 'The Move command is used to change the position of a 3D object without changing its size or shape.',
    narrationText: 'The Move command is used to change the position of a 3D object without changing its size or shape.',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 0.01,
    holdVideo: true,
    waitForNarrationBeforeVideo: true,
  },
  {
    id: 'select-geo-step-1',
    title: '1. Select Move Tool',
    customText: 'From the Icon Menu, select Move.',
    narrationText: 'From the Icon Menu, select Move.',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 2.5,
    overlays: [
      {
        id: 'highlight-move-group',
        type: 'highlight',
        startTime: 0.3,
        endTime: 2.4,
        target: { x: 0.91, y: 0.362, width: 0.07, height: 0.025 },
        label: 'Move / Copy / Delete',
        labelPosition: 'left',
        animation: 'pulse',
      },
      {
        id: 'highlight-move-icon',
        type: 'highlight',
        startTime: 0.8,
        endTime: 2.5,
        target: { x: 0.910, y: 0.387, width: 0.0188, height: 0.032 },
        label: 'Move Tool',
        labelPosition: 'bottom',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'select-geo-step-2',
    title: '2. Select the Object',
    customText: 'Left-click the object you want to move.',
    narrationText: 'Left-click the object you want to move.',
    narrateTitle: false,
    videoStart: 2.5,
    videoEnd: 6.0,
    overlays: [
      {
        id: 'highlight-prompt-target',
        type: 'highlight',
        startTime: 2.5,
        endTime: 6.0,
        target: { x: 0.005, y: 0.970, width: 0.220, height: 0.028 },
        label: 'Prompt: Target Element GO',
        labelPosition: 'top',
        animation: 'pulse',
      },
      {
        id: 'highlight-box-selection',
        type: 'highlight',
        startTime: 4.6,
        endTime: 6.0,
        target: { x: 0.28, y: 0.55, width: 0.28, height: 0.35 },
        label: 'Select Object',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'select-geo-quiz-1',
    title: 'Knowledge Check: Selection Confirmation',
    customText: 'How do you confirm your geometry selection before entering movement distance in iCAD SX?',
    videoStart: 6.0,
    videoEnd: 6.0,
    holdVideo: true,
    quizData: {
      question: 'How do you confirm your geometry selection before entering movement distance in iCAD SX?',
      options: [
        {
          text: 'Click GO or press Enter',
          isCorrect: true,
          feedback: 'Correct! Clicking GO or pressing Enter finishes selection and opens coordinate entry.',
        },
        {
          text: 'Press Esc',
          isCorrect: false,
          feedback: 'Incorrect. Esc cancels the active operation.',
        },
        {
          text: 'Right-click the empty workspace',
          isCorrect: false,
          feedback: 'Incorrect. Right-clicking is used for contextual menus or origin display.',
        },
      ],
    },
  },
  {
    id: 'select-geo-step-3',
    title: '3. Enter Movement Distance',
    customText: 'In the Item Entry, enter the movement distance for:\n* X-axis\n* Y-axis\n* Z-axis\n\nThen press <b>Enter</b> to move the object.\n\n<b>Example</b>:\n <b>X= 50mm</b>, <b>Y= 0mm</b>, <b>Z= 0mm</b>\n',
    preserveText: true,
    narrationText: 'In the Item Entry, enter the movement distance for X, Y, and Z axes, then press Enter to move the object.',
    narrateTitle: false,
    videoStart: 6.0,
    videoEnd: 8.5,
    overlays: [
      {
        id: 'highlight-movement-entry',
        type: 'highlight',
        startTime: 6.0,
        endTime: 8.5,
        target: { x: 0.055, y: 0.940, width: 0.220, height: 0.038 },
        label: 'Movement Entry: X = 30.0',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'select-geo-step-4',
    title: '4. Confirm & Verify Movement',
    customText: 'Confirm the movement and verify that the object moves to its new position.',
    narrationText: 'Confirm the movement and verify that the object moves to its new position.',
    narrateTitle: false,
    videoStart: 8.5,
    videoEnd: 10.36,
  },
  {
    id: 'select-geo-recap',
    title: 'Move Recap',
    customText: 'Select Move → Select Object → Enter Movement Distance → Confirm',
    videoStart: 10.36,
    videoEnd: 10.36,
    holdVideo: true,
    recapData: {
      title: 'Move (How to Use Move)',
      items: [
        'From the Icon Menu, select Move',
        'Left-click the object you want to move',
        'In the Item Entry, enter the movement distance (X, Y, Z)',
        'Press Enter to move the object',
      ],
    },
  },
];

export const MOVE_VIDEO_STEPS = SELECTING_GEOMETRY_VIDEO_STEPS;

// ==========================================
// 2. ROTATE (回転) VIDEO
// ==========================================
export const ROTATE_VIDEO_STEPS: LessonVideoStep[] = [
  {
    id: 'rotate-step-0',
    title: 'Rotate Introduction',
    customText: 'The Rotate command is used to turn a 3D object around a selected axis without changing its size or shape.',
    narrationText: 'The Rotate command is used to turn a 3D object around a selected axis without changing its size or shape.',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 0.01,
    holdVideo: true,
    waitForNarrationBeforeVideo: true,
  },
  {
    id: 'rotate-step-1',
    title: '1. Select Rotate',
    customText: 'From the Icon Menu on the right toolbar, select 回転 (Rotate) under 移動・コピー・削除 (Move / Copy / Delete).',
    narrationText: 'From the Icon Menu, select Rotate.',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 3.0,
    overlays: [
      {
        id: 'highlight-rotate-group',
        type: 'highlight',
        startTime: 0.3,
        endTime: 2.9,
        target: { x: 0.895, y: 0.355, width: 0.080, height: 0.025 },
        label: 'Move / Copy / Delete',
        labelPosition: 'left',
        animation: 'pulse',
      },
      {
        id: 'highlight-rotate-icon',
        type: 'highlight',
        startTime: 0.8,
        endTime: 3.0,
        target: { x: 0.925, y: 0.380, width: 0.028, height: 0.042 },
        label: 'Rotate Tool',
        labelPosition: 'left',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'rotate-step-2',
    title: '2. Select the Object',
    customText: 'Left-click the object you want to rotate, then click GO (or press Enter) to confirm your selection.',
    narrationText: 'Left-click the object you want to rotate, then click GO to confirm your selection.',
    narrateTitle: false,
    videoStart: 3.0,
    videoEnd: 5.7,
    overlays: [
      {
        id: 'highlight-prompt-target',
        type: 'highlight',
        startTime: 3.0,
        endTime: 5.7,
        target: { x: 0.005, y: 0.970, width: 0.220, height: 0.028 },
        label: 'Prompt: Target Element GO',
        labelPosition: 'top',
        animation: 'pulse',
      },
      {
        id: 'highlight-rotate-object',
        type: 'highlight',
        startTime: 3.2,
        endTime: 5.7,
        target: { x: 0.430, y: 0.350, width: 0.260, height: 0.320 },
        label: 'Selected Object',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'rotate-step-3',
    title: '3. Set the Rotation Axis',
    customText: 'Select 2 points to define the axis where the object will rotate.',
    narrationText: 'Select two points to define the axis where the object will rotate.',
    narrateTitle: false,
    videoStart: 5.7,
    videoEnd: 9.5,
    overlays: [
      {
        id: 'highlight-axis-pt1',
        type: 'highlight',
        startTime: 5.7,
        endTime: 7.5,
        target: { x: 0.425, y: 0.510, width: 0.035, height: 0.035 },
        label: 'Axis Point 1',
        labelPosition: 'top',
        animation: 'pulse',
      },
      {
        id: 'highlight-axis-pt2',
        type: 'highlight',
        startTime: 7.5,
        endTime: 9.5,
        target: { x: 0.555, y: 0.665, width: 0.035, height: 0.035 },
        label: 'Axis Point 2',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'rotate-quiz-1',
    title: 'Knowledge Check: Rotation Axis',
    customText: 'How do you define the rotation axis for a 3D object in iCAD SX?',
    videoStart: 9.5,
    videoEnd: 9.5,
    holdVideo: true,
    quizData: {
      question: 'How do you define the rotation axis for a 3D object in iCAD SX?',
      options: [
        {
          text: 'Select 2 points to define the axis',
          isCorrect: true,
          feedback: 'Correct! Selecting 2 points defines the rotational axis line in 3D space.',
        },
        {
          text: 'Select 3 points on any surface',
          isCorrect: false,
          feedback: 'Incorrect. 3 points define a plane (used for mirroring), whereas an axis needs 2 points.',
        },
        {
          text: 'Only click the origin center',
          isCorrect: false,
          feedback: 'Incorrect. The rotation axis can be placed anywhere by picking 2 points.',
        },
      ],
    },
  },
  {
    id: 'rotate-step-4',
    title: '4. Enter the Rotation Angle',
    customText: 'In the Item Entry, enter the desired rotation angle (e.g. 90°) and press Enter to complete the rotation.',
    narrationText: 'In the Item Entry, enter the desired rotation angle, such as ninety degrees, and press Enter to complete the rotation.',
    narrateTitle: false,
    videoStart: 9.5,
    videoEnd: 12.9,
    overlays: [
      {
        id: 'highlight-angle-entry',
        type: 'highlight',
        startTime: 9.5,
        endTime: 12.9,
        target: { x: 0.065, y: 0.950, width: 0.100, height: 0.035 },
        label: 'Angle: 90.0°',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'rotate-step-5',
    title: '5. Verify Rotated Object',
    customText: 'The 3D object turns to the specified 90° angle around the defined axis without changing its size or shape.',
    narrationText: 'The object turns to the specified ninety degree angle around the defined axis without changing its size or shape.',
    narrateTitle: false,
    videoStart: 12.9,
    videoEnd: 16.31,
  },
  {
    id: 'rotate-recap',
    title: 'Rotate Recap',
    customText: 'Select Rotate → Select Object → Set Axis → Enter Angle → Confirm',
    videoStart: 16.31,
    videoEnd: 16.31,
    holdVideo: true,
    recapData: {
      title: 'Rotate (How to Rotate an Object)',
      items: [
        'Select Rotate from the Icon Menu',
        'Left-click the object you want to rotate and confirm with GO',
        'Select 2 points to define the rotation axis',
        'In the Item Entry, enter the desired rotation angle (e.g. 90°)',
        'Press Enter to complete the rotation',
      ],
    },
  },
];

// ==========================================
// 3. MIRROR (ミラー) VIDEO
// ==========================================
export const MIRROR_VIDEO_STEPS: LessonVideoStep[] = [
  {
    id: 'mirror-step-0',
    title: 'Mirror Introduction',
    customText: 'The Mirror command is used to create a mirrored copy of a 3D object across a selected plane.',
    narrationText: 'The Mirror command is used to create a mirrored copy of a 3D object across a selected plane.',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 0.01,
    holdVideo: true,
    waitForNarrationBeforeVideo: true,
  },
  {
    id: 'mirror-step-1',
    title: '1. Select Mirror',
    customText: 'From the Icon Menu on the right toolbar, select ミラー (Mirror) under 移動・コピー・削除 (Move / Copy / Delete).',
    narrationText: 'From the Icon Menu, select Mirror.',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 3.0,
    overlays: [
      {
        id: 'highlight-mirror-group',
        type: 'highlight',
        startTime: 0.3,
        endTime: 2.9,
        target: { x: 0.895, y: 0.355, width: 0.080, height: 0.025 },
        label: 'Move / Copy / Delete',
        labelPosition: 'left',
        animation: 'pulse',
      },
      {
        id: 'highlight-mirror-icon',
        type: 'highlight',
        startTime: 0.8,
        endTime: 3.0,
        target: { x: 0.948, y: 0.380, width: 0.026, height: 0.042 },
        label: 'Mirror Tool',
        labelPosition: 'left',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'mirror-step-2',
    title: '2. Select the Object',
    customText: 'Left-click the object you want to mirror, then confirm with GO (or press Enter).',
    narrationText: 'Left-click the object you want to mirror, then click GO to confirm your selection.',
    narrateTitle: false,
    videoStart: 3.0,
    videoEnd: 6.5,
    overlays: [
      {
        id: 'highlight-prompt-target',
        type: 'highlight',
        startTime: 3.0,
        endTime: 6.5,
        target: { x: 0.005, y: 0.970, width: 0.220, height: 0.028 },
        label: 'Prompt: Target Element GO',
        labelPosition: 'top',
        animation: 'pulse',
      },
      {
        id: 'highlight-mirror-object',
        type: 'highlight',
        startTime: 3.5,
        endTime: 6.5,
        target: { x: 0.430, y: 0.350, width: 0.260, height: 0.320 },
        label: 'Selected Object',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'mirror-step-3',
    title: '3. Set the Mirror Plane',
    customText: 'Select 3 points to define the plane where the object will be mirrored (or click a face).',
    narrationText: 'Select three points to define the plane where the object will be mirrored, or click a face.',
    narrateTitle: false,
    videoStart: 6.5,
    videoEnd: 13.8,
    overlays: [
      {
        id: 'highlight-plane-pt1',
        type: 'highlight',
        startTime: 6.5,
        endTime: 8.8,
        target: { x: 0.470, y: 0.560, width: 0.035, height: 0.035 },
        label: 'Plane Point 1',
        labelPosition: 'top',
        animation: 'pulse',
      },
      {
        id: 'highlight-plane-pt2',
        type: 'highlight',
        startTime: 8.8,
        endTime: 11.5,
        target: { x: 0.480, y: 0.620, width: 0.035, height: 0.035 },
        label: 'Plane Point 2',
        labelPosition: 'top',
        animation: 'pulse',
      },
      {
        id: 'highlight-plane-pt3',
        type: 'highlight',
        startTime: 11.5,
        endTime: 13.8,
        target: { x: 0.585, y: 0.525, width: 0.035, height: 0.035 },
        label: 'Plane Point 3',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'mirror-quiz-1',
    title: 'Knowledge Check: Mirror Plane',
    customText: 'How can you define the mirror plane for a 3D object in iCAD SX?',
    videoStart: 13.8,
    videoEnd: 13.8,
    holdVideo: true,
    quizData: {
      question: 'How can you define the mirror plane for a 3D object in iCAD SX?',
      options: [
        {
          text: 'Select 3 points or click a face',
          isCorrect: true,
          feedback: 'Correct! Selecting 3 points or picking a face defines the reflection plane.',
        },
        {
          text: 'Select only 1 point',
          isCorrect: false,
          feedback: 'Incorrect. 1 point defines a location, but 3 points are needed to define a 3D plane.',
        },
        {
          text: 'Enter a rotation angle',
          isCorrect: false,
          feedback: 'Incorrect. Angle input is used for Rotate, whereas Mirror requires a plane.',
        },
      ],
    },
  },
  {
    id: 'mirror-step-4',
    title: '4. Confirm & Verify',
    customText: 'Confirm the selection to create the symmetrical mirrored copy on the opposite side.',
    narrationText: 'Confirm the selection to create the mirrored result.',
    narrateTitle: false,
    videoStart: 13.8,
    videoEnd: 17.10,
    overlays: [
      {
        id: 'highlight-mirror-result',
        type: 'highlight',
        startTime: 13.8,
        endTime: 17.10,
        target: { x: 0.430, y: 0.350, width: 0.320, height: 0.320 },
        label: 'Mirrored Symmetrical Result',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'mirror-recap',
    title: 'Mirror Recap',
    customText: 'Select Mirror → Select Object → Select Mirror Plane → Confirm',
    videoStart: 17.10,
    videoEnd: 17.10,
    holdVideo: true,
    recapData: {
      title: 'Mirror (How to Mirror an Object)',
      items: [
        'Select Mirror from the Icon Menu',
        'Left-click the object you want to mirror',
        'Select 3 points or click a face to set the mirror plane',
        'Confirm to create the mirrored result',
      ],
    },
  },
];

// ==========================================
// 4. COPY (コピー) VIDEO
// ==========================================
export const COPY_VIDEO_STEPS: LessonVideoStep[] = [
  {
    id: 'copy-step-0',
    title: 'Copy Introduction',
    customText: 'The Copy command is used to create one or more duplicates of a 3D object while keeping the original object.',
    narrationText: 'The Copy command is used to create one or more duplicates of a 3D object while keeping the original object.',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 0.01,
    holdVideo: true,
    waitForNarrationBeforeVideo: true,
  },
  {
    id: 'copy-step-1',
    title: '1. Select Copy',
    customText: 'From the Icon Menu on the right toolbar, select 複写 (Copy) under 移動・コピー・削除 (Move / Copy / Delete).',
    narrationText: 'From the Icon Menu, select Copy.',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 3.0,
    overlays: [
      {
        id: 'highlight-copy-group',
        type: 'highlight',
        startTime: 0.3,
        endTime: 2.9,
        target: { x: 0.895, y: 0.355, width: 0.080, height: 0.025 },
        label: 'Move / Copy / Delete',
        labelPosition: 'left',
        animation: 'pulse',
      },
      {
        id: 'highlight-copy-icon',
        type: 'highlight',
        startTime: 0.8,
        endTime: 3.0,
        target: { x: 0.925, y: 0.380, width: 0.028, height: 0.042 },
        label: 'Copy Tool',
        labelPosition: 'left',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'copy-step-2',
    title: '2. Select the Object',
    customText: 'Left-click the object you want to copy, then click GO (or press Enter) to confirm your selection.',
    narrationText: 'Left-click the object you want to copy.',
    narrateTitle: false,
    videoStart: 3.0,
    videoEnd: 5.5,
    overlays: [
      {
        id: 'highlight-prompt-target',
        type: 'highlight',
        startTime: 3.0,
        endTime: 5.5,
        target: { x: 0.005, y: 0.970, width: 0.220, height: 0.028 },
        label: 'Prompt: Target Element GO',
        labelPosition: 'top',
        animation: 'pulse',
      },
      {
        id: 'highlight-copy-object',
        type: 'highlight',
        startTime: 3.2,
        endTime: 5.5,
        target: { x: 0.430, y: 0.350, width: 0.260, height: 0.320 },
        label: 'Object to Copy',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'copy-step-3',
    title: '3. Enter the Copy Distance',
    customText: 'In the Item Entry, enter the movement distance for X-axis, Y-axis, and Z-axis, then enter the number of copies and press Enter to complete the command.',
    narrationText: 'In the Item Entry, enter the movement distance for X, Y, and Z axes, then enter the number of copies and press Enter to complete the command.',
    narrateTitle: false,
    videoStart: 5.5,
    videoEnd: 11.0,
    overlays: [
      {
        id: 'highlight-copy-entry',
        type: 'highlight',
        startTime: 5.5,
        endTime: 11.0,
        target: { x: 0.005, y: 0.950, width: 0.350, height: 0.038 },
        label: 'Distance & Copy Count',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'copy-quiz-1',
    title: 'Knowledge Check: Copy Command',
    customText: 'What happens to the original object when you use the Copy command in iCAD SX?',
    videoStart: 11.0,
    videoEnd: 11.0,
    holdVideo: true,
    quizData: {
      question: 'What happens to the original object when you use the Copy command in iCAD SX?',
      options: [
        {
          text: 'The original object is kept while one or more duplicates are created',
          isCorrect: true,
          feedback: 'Correct! Unlike Move, Copy retains the original object and places duplicates at the specified distance.',
        },
        {
          text: 'The original object is deleted and replaced by a duplicate',
          isCorrect: false,
          feedback: 'Incorrect. The Copy command preserves the original object.',
        },
        {
          text: 'The original object changes its size and orientation',
          isCorrect: false,
          feedback: 'Incorrect. Copy creates identical duplicates without modifying the original object.',
        },
      ],
    },
  },
  {
    id: 'copy-step-4',
    title: '4. Verify Duplicate Copies',
    customText: 'Duplicate copies appear at the specified distance while keeping the original object intact.',
    narrationText: 'Duplicate copies appear at the specified distance while keeping the original object intact.',
    narrateTitle: false,
    videoStart: 11.0,
    videoEnd: 15.38,
  },
  {
    id: 'copy-recap',
    title: 'Copy Recap',
    customText: 'Select Copy → Select Object → Enter X, Y, Z Distance → Enter Number of Copies → Confirm',
    videoStart: 15.38,
    videoEnd: 15.38,
    holdVideo: true,
    recapData: {
      title: 'Copy (How to Use Copy)',
      items: [
        'From the Icon Menu, select Copy',
        'Left-click the object you want to copy',
        'In the Item Entry, enter the movement distance for X, Y, and Z axes',
        'Enter the number of copies you want to create',
        'Press Enter to complete the command',
      ],
    },
  },
];

// ==========================================
// 5. ROTATE COPY (回転複写) VIDEO
// ==========================================
export const ROTATE_COPY_VIDEO_STEPS: LessonVideoStep[] = [
  {
    id: 'rotate-copy-step-0',
    title: 'Rotate Copy Introduction',
    customText: 'The Rotate Copy command works like the Rotate tool, but it creates a rotated duplicate while keeping the original object.',
    narrationText: 'The Rotate Copy command works like the Rotate tool, but it creates a rotated duplicate while keeping the original object.',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 0.01,
    holdVideo: true,
    waitForNarrationBeforeVideo: true,
  },
  {
    id: 'rotate-copy-step-1',
    title: '1. Select Rotate Copy',
    customText: 'From the Icon Menu on the right toolbar, select 回転複写 (Rotate Copy) under 移動・コピー・削除 (Move / Copy / Delete).',
    narrationText: 'From the Icon Menu, select Rotate Copy.',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 6.5,
    overlays: [
      {
        id: 'highlight-rotate-copy-group',
        type: 'highlight',
        startTime: 3.0,
        endTime: 6.4,
        target: { x: 0.895, y: 0.355, width: 0.080, height: 0.025 },
        label: 'Move / Copy / Delete',
        labelPosition: 'left',
        animation: 'pulse',
      },
      {
        id: 'highlight-rotate-copy-icon',
        type: 'highlight',
        startTime: 3.5,
        endTime: 6.5,
        target: { x: 0.940, y: 0.420, width: 0.030, height: 0.040 },
        label: 'Rotate Copy Tool',
        labelPosition: 'left',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'rotate-copy-step-2',
    title: '2. Select the Object',
    customText: 'Left-click the object you want to copy and rotate, then confirm your selection.',
    narrationText: 'Left-click the object you want to copy and rotate.',
    narrateTitle: false,
    videoStart: 6.5,
    videoEnd: 9.0,
    overlays: [
      {
        id: 'highlight-prompt-target',
        type: 'highlight',
        startTime: 6.5,
        endTime: 9.0,
        target: { x: 0.005, y: 0.970, width: 0.220, height: 0.028 },
        label: 'Prompt: Target Element GO',
        labelPosition: 'top',
        animation: 'pulse',
      },
      {
        id: 'highlight-rotate-copy-object',
        type: 'highlight',
        startTime: 6.8,
        endTime: 9.0,
        target: { x: 0.370, y: 0.500, width: 0.150, height: 0.150 },
        label: 'Object to Rotate & Copy',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'rotate-copy-step-3',
    title: '3. Set the Rotation Axis',
    customText: 'Select 2 points to define the axis of rotation.',
    narrationText: 'Select two points to define the axis of rotation.',
    narrateTitle: false,
    videoStart: 9.0,
    videoEnd: 13.5,
    overlays: [
      {
        id: 'highlight-axis-pt1',
        type: 'highlight',
        startTime: 9.0,
        endTime: 11.2,
        target: { x: 0.550, y: 0.460, width: 0.030, height: 0.030 },
        label: 'Axis Point 1',
        labelPosition: 'top',
        animation: 'pulse',
      },
      {
        id: 'highlight-axis-pt2',
        type: 'highlight',
        startTime: 11.2,
        endTime: 13.5,
        target: { x: 0.550, y: 0.675, width: 0.030, height: 0.030 },
        label: 'Axis Point 2',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'rotate-copy-step-4',
    title: '4. Enter the Rotation Angle',
    customText: 'In the Item Entry, enter the desired angle (e.g. 90°) and number of copies, then press Enter to create the rotated copy.',
    narrationText: 'In the Item Entry, enter the desired angle, such as ninety degrees, and press Enter to create the rotated copy.',
    narrateTitle: false,
    videoStart: 13.5,
    videoEnd: 19.0,
    overlays: [
      {
        id: 'highlight-angle-count-entry',
        type: 'highlight',
        startTime: 13.5,
        endTime: 19.0,
        target: { x: 0.005, y: 0.950, width: 0.220, height: 0.038 },
        label: 'Angle: 90° | Count: 3',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'rotate-copy-quiz-1',
    title: 'Knowledge Check: Rotate Copy',
    customText: 'How does the Rotate Copy command differ from the standard Rotate command in iCAD SX?',
    videoStart: 19.0,
    videoEnd: 19.0,
    holdVideo: true,
    quizData: {
      question: 'How does the Rotate Copy command differ from the standard Rotate command in iCAD SX?',
      options: [
        {
          text: 'It creates a rotated duplicate while keeping the original object intact',
          isCorrect: true,
          feedback: 'Correct! Rotate Copy creates one or more duplicates at the specified angle while retaining the original object.',
        },
        {
          text: 'It permanently changes the size and orientation of the original object',
          isCorrect: false,
          feedback: 'Incorrect. Rotate Copy creates identical copies without changing part dimensions.',
        },
        {
          text: 'It deletes the original object after rotating it to a new location',
          isCorrect: false,
          feedback: 'Incorrect. The standard Rotate moves the original, whereas Rotate Copy preserves the original.',
        },
      ],
    },
  },
  {
    id: 'rotate-copy-step-5',
    title: '5. Verify Rotated Copies',
    customText: 'The rotated copies are created around the specified axis at 90° intervals while keeping the original object intact.',
    narrationText: 'The rotated copies are created around the specified axis at ninety degree intervals while keeping the original object intact.',
    narrateTitle: false,
    videoStart: 19.0,
    videoEnd: 24.167,
  },
  {
    id: 'rotate-copy-recap',
    title: 'Rotate Copy Recap',
    customText: 'Select Rotate Copy → Select Object → Set Axis → Enter Angle → Confirm',
    videoStart: 24.167,
    videoEnd: 24.167,
    holdVideo: true,
    recapData: {
      title: 'Rotate Copy (How to Use Rotate Copy)',
      items: [
        'From the Icon Menu, select Rotate Copy',
        'Left-click the object you want to copy and rotate',
        'Select 2 points to define the axis of rotation',
        'In the Item Entry, enter the desired angle (e.g. 90°)',
        'Press Enter to create the rotated copy',
      ],
    },
  },
];

// ==========================================
// 6. MIRROR COPY (ミラー複写) VIDEO
// ==========================================
export const MIRROR_COPY_VIDEO_STEPS: LessonVideoStep[] = [
  {
    id: 'mirror-copy-step-0',
    title: 'Mirror Copy Introduction',
    customText: 'The Mirror Copy command works like the Mirror tool, but it creates a mirrored duplicate while keeping the original object.',
    narrationText: 'The Mirror Copy command works like the Mirror tool, but it creates a mirrored duplicate while keeping the original object.',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 0.01,
    holdVideo: true,
    waitForNarrationBeforeVideo: true,
  },
  {
    id: 'mirror-copy-step-1',
    title: '1. Select Mirror Copy',
    customText: 'From the Icon Menu on the right toolbar, select ミラー複写 (Mirror Copy) under 移動・コピー・削除 (Move / Copy / Delete).',
    narrationText: 'From the Icon Menu, select Mirror Copy.',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 5.0,
    overlays: [
      {
        id: 'highlight-mirror-copy-group',
        type: 'highlight',
        startTime: 1.0,
        endTime: 4.9,
        target: { x: 0.895, y: 0.355, width: 0.080, height: 0.025 },
        label: 'Move / Copy / Delete',
        labelPosition: 'left',
        animation: 'pulse',
      },
      {
        id: 'highlight-mirror-copy-icon',
        type: 'highlight',
        startTime: 1.5,
        endTime: 5.0,
        target: { x: 0.940, y: 0.420, width: 0.030, height: 0.040 },
        label: 'Mirror Copy Tool',
        labelPosition: 'left',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'mirror-copy-step-2',
    title: '2. Select the Object',
    customText: 'Left-click the objects you want to copy and mirror, then click GO (or press Enter) to confirm selection.',
    narrationText: 'Left-click the object you want to copy and mirror.',
    narrateTitle: false,
    videoStart: 5.0,
    videoEnd: 12.0,
    overlays: [
      {
        id: 'highlight-prompt-target',
        type: 'highlight',
        startTime: 5.0,
        endTime: 12.0,
        target: { x: 0.005, y: 0.970, width: 0.220, height: 0.028 },
        label: 'Prompt: Target Element GO',
        labelPosition: 'top',
        animation: 'pulse',
      },
      {
        id: 'highlight-mirror-copy-obj1',
        type: 'highlight',
        startTime: 5.5,
        endTime: 12.0,
        target: { x: 0.310, y: 0.470, width: 0.080, height: 0.090 },
        label: 'Component 1',
        labelPosition: 'top',
        animation: 'pulse',
      },
      {
        id: 'highlight-mirror-copy-obj2',
        type: 'highlight',
        startTime: 8.0,
        endTime: 12.0,
        target: { x: 0.500, y: 0.280, width: 0.080, height: 0.090 },
        label: 'Component 2',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'mirror-copy-step-3',
    title: '3. Set the Mirror Plane',
    customText: 'Select 3 points to define the mirror plane (or select a planar face to use as the mirror plane).',
    narrationText: 'Select three points to define the mirror plane, or select a face to use as the mirror plane.',
    narrateTitle: false,
    videoStart: 12.0,
    videoEnd: 21.5,
    overlays: [
      {
        id: 'highlight-plane-pt1',
        type: 'highlight',
        startTime: 13.0,
        endTime: 17.5,
        target: { x: 0.430, y: 0.660, width: 0.030, height: 0.030 },
        label: 'Plane Point 1',
        labelPosition: 'top',
        animation: 'pulse',
      },
      {
        id: 'highlight-plane-pt2',
        type: 'highlight',
        startTime: 17.5,
        endTime: 21.5,
        target: { x: 0.650, y: 0.400, width: 0.030, height: 0.030 },
        label: 'Plane Point 2',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'mirror-copy-quiz-1',
    title: 'Knowledge Check: Mirror Copy',
    customText: 'What is the key difference between Mirror and Mirror Copy in iCAD SX?',
    videoStart: 21.5,
    videoEnd: 21.5,
    holdVideo: true,
    quizData: {
      question: 'What is the key difference between Mirror and Mirror Copy in iCAD SX?',
      options: [
        {
          text: 'Mirror Copy creates a mirrored duplicate while keeping the original object intact',
          isCorrect: true,
          feedback: 'Correct! Mirror Copy retains the original components and duplicates them across the symmetry plane.',
        },
        {
          text: 'Mirror Copy moves the original object without keeping the original',
          isCorrect: false,
          feedback: 'Incorrect. The standard Mirror command moves the original object, while Mirror Copy preserves the original.',
        },
        {
          text: 'Mirror Copy changes the scale of the object',
          isCorrect: false,
          feedback: 'Incorrect. Mirror Copy creates an identical mirrored replica without scaling.',
        },
      ],
    },
  },
  {
    id: 'mirror-copy-step-4',
    title: '4. Confirm Mirrored Copy',
    customText: 'Confirm the selection to create the mirrored copy on the opposite side while keeping the original objects.',
    narrationText: 'Confirm the selection to create the mirrored copy.',
    narrateTitle: false,
    videoStart: 21.5,
    videoEnd: 25.517,
  },
  {
    id: 'mirror-copy-recap',
    title: 'Mirror Copy Recap',
    customText: 'Select Mirror Copy → Select Object → Set Mirror Plane → Confirm',
    videoStart: 25.517,
    videoEnd: 25.517,
    holdVideo: true,
    recapData: {
      title: 'Mirror Copy (How to Use Mirror Copy)',
      items: [
        'From the Icon Menu, select Mirror Copy',
        'Left-click the object you want to copy and mirror',
        'Select 3 points to define the mirror plane (or select a face)',
        'Confirm the selection to create the mirrored copy',
      ],
    },
  },
];

// ==========================================
// 7. DELETE (削除) VIDEO
// ==========================================
export const DELETE_VIDEO_STEPS: LessonVideoStep[] = [
  {
    id: 'delete-step-0',
    title: 'Delete Introduction',
    customText: 'The Delete command is used to remove an unwanted object from the 3D model.',
    narrationText: 'The Delete command is used to remove an unwanted object from the 3D model.',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 0.01,
    holdVideo: true,
    waitForNarrationBeforeVideo: true,
  },
  {
    id: 'delete-step-1',
    title: '1. Select Delete',
    customText: 'From the Icon Menu on the right toolbar, select 削除 (Delete) under 移動・コピー・削除 (Move / Copy / Delete).',
    narrationText: 'From the Icon Menu, select Delete.',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 3.5,
    overlays: [
      {
        id: 'highlight-delete-group',
        type: 'highlight',
        startTime: 0.5,
        endTime: 3.4,
        target: { x: 0.895, y: 0.355, width: 0.080, height: 0.025 },
        label: 'Move / Copy / Delete',
        labelPosition: 'left',
        animation: 'pulse',
      },
      {
        id: 'highlight-delete-icon',
        type: 'highlight',
        startTime: 1.0,
        endTime: 3.5,
        target: { x: 0.965, y: 0.380, width: 0.025, height: 0.042 },
        label: 'Delete Tool',
        labelPosition: 'left',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'delete-step-2',
    title: '2. Select the Object',
    customText: 'Left-click the object you want to remove.',
    narrationText: 'Left-click the object you want to remove.',
    narrateTitle: false,
    videoStart: 3.5,
    videoEnd: 7.5,
    overlays: [
      {
        id: 'highlight-prompt-target',
        type: 'highlight',
        startTime: 3.5,
        endTime: 7.5,
        target: { x: 0.005, y: 0.970, width: 0.220, height: 0.028 },
        label: 'Prompt: Target Element',
        labelPosition: 'top',
        animation: 'pulse',
      },
      {
        id: 'highlight-delete-object',
        type: 'highlight',
        startTime: 4.0,
        endTime: 7.5,
        target: { x: 0.500, y: 0.550, width: 0.280, height: 0.250 },
        label: 'Object to Remove',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'delete-quiz-1',
    title: 'Knowledge Check: Delete Confirmation',
    customText: 'How do you confirm the deletion of an object in iCAD SX?',
    videoStart: 7.5,
    videoEnd: 7.5,
    holdVideo: true,
    quizData: {
      question: 'How do you confirm the deletion of an object in iCAD SX?',
      options: [
        {
          text: 'Click GO or press Enter to confirm deletion',
          isCorrect: true,
          feedback: 'Correct! Confirming with GO or pressing Enter deletes the selected object.',
        },
        {
          text: 'Press Esc',
          isCorrect: false,
          feedback: 'Incorrect. Pressing Esc cancels the delete operation.',
        },
        {
          text: 'Double-click the viewport background',
          isCorrect: false,
          feedback: 'Incorrect. Viewport clicking does not confirm deletion.',
        },
      ],
    },
  },
  {
    id: 'delete-step-3',
    title: '3. Confirm & Verify Deletion',
    customText: 'Confirm the selection to remove the unwanted object from the 3D model.',
    narrationText: 'Confirm the selection to delete the object.',
    narrateTitle: false,
    videoStart: 7.5,
    videoEnd: 11.92,
    overlays: [
      {
        id: 'highlight-delete-prompt-go',
        type: 'highlight',
        startTime: 7.5,
        endTime: 9.5,
        target: { x: 0.005, y: 0.970, width: 0.200, height: 0.028 },
        label: 'Prompt: GO to Delete',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'delete-recap',
    title: 'Delete Recap',
    customText: 'Select Delete → Select Object → Confirm',
    videoStart: 11.92,
    videoEnd: 11.92,
    holdVideo: true,
    recapData: {
      title: 'Delete (How to Use Delete)',
      items: [
        'From the Icon Menu, select Delete',
        'Left-click the object you want to remove',
        'Confirm the selection to delete the object',
      ],
    },
  },
];

export default SELECTING_GEOMETRY_VIDEO_STEPS;
