import { LessonVideoStep } from './types';

export const ORIGIN_AXES_VIDEO_STEPS: LessonVideoStep[] = [
  {
    id: 'origin-video-intro',
    title: 'The Origin & Axes Demonstration',
    customText: 'Observe how the Origin (0, 0, 0) and the X, Y, and Z axes establish coordinates in 3D space.',
    videoStart: 0,
    videoEnd: 5,
  },
  {
    id: 'origin-video-inspect',
    title: 'Coordinate Orientation',
    customText: 'As the view rotates, note how the axes indicate model orientation.',
    videoStart: 5,
    videoEnd: 10,
    holdVideo: true,
  },
];

export const ORIGIN_LAYOUT_VIDEO_STEPS: LessonVideoStep[] = [
  {
    id: 'origin-layout-step-1',
    title: '1. Select Change 3D Part Layout',
    customText: 'From the icon menu, navigate to パーツ (3D PARTS ) → パーツのレイアウトを変更する (Change 3D Part Layout).',
    narrationText: 'From the icon menu, navigate to 3D Parts then click the Change 3D Part Layout.',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 9,
    overlays: [
      {
        id: 'highlight-vertical-tab-parts',
        type: 'highlight',
        startTime: 2.5,
        endTime: 4.5,
        target: { x: 0.979, y: 0.214, width: 0.02, height: 0.045 },
        label: '3D PARTS',
        labelPosition: 'left',
        animation: 'pulse',
      },
      {
        id: 'highlight-header-parts',
        type: 'highlight',
        startTime: 2.5,
        endTime: 4.5,
        target: { x: 0.909, y: 0.119, width: 0.07, height: 0.03 },
        label: '3D PARTS',
        labelPosition: 'left',
        animation: 'pulse',
      },
      {
        id: 'highlight-icon-change-layout',
        type: 'highlight',
        startTime: 5.0,
        endTime: 9.0,
        target: { x: 0.959, y: 0.175, width: 0.022, height: 0.039 },
        label: 'Change 3D Part Layout',
        labelPosition: 'left',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'origin-layout-step-2',
    title: '',
    customText: 'Right-click on the workspace to show the current location of the origin.',
    videoStart: 5,
    videoEnd: 9.5,
    overlays: [
      {
        id: 'arrow-current-origin',
        type: 'arrow',
        startTime: 7.9,
        endTime: 9.5,
        line: {
          start: { x: 0.605, y: 0.765 },
          end: { x: 0.536, y: 0.67 },
          controlPoint: { x: 0.565, y: 0.75 },
        },
        label: 'Current Origin Position',
        labelPosition: 'bottom',
        animation: 'pulse',
        narrate: false,
      },
    ],
  },
  {
    id: 'origin-layout-step-3',
    title: '',
    customText: 'Left-click on the point of the desired new location of origin.',
    videoStart: 9.5,
    videoEnd: 11,
    waitForNarrationBeforeVideo: true,
    overlays: [
      {
        id: 'highlight-point-1',
        type: 'highlight',
        startTime: 9.0,
        endTime: 11,
        target: { x: 0.4721, y: 0.692, width: 0.02, height: 0.03 },
        label: 'Point 1: New Origin Location',
        labelPosition: 'bottom',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'origin-layout-step-4',
    title: '',
    customText: 'Left-click on a second point to set the X-axis direction.',
    videoStart: 11,
    videoEnd: 15,
    overlays: [
      {
        id: 'highlight-point-2',
        type: 'highlight',
        startTime: 13,
        endTime: 15,
        target: { x: 0.628, y: 0.56, width: 0.02, height: 0.03 },
        label: 'Point 2: X-Axis',
        labelPosition: 'bottom',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'origin-layout-step-5',
    title: '',
    customText: 'Left-click on a third point to set the Y-axis. The resulting XY-plane establishes the front view.',
    videoStart: 15,
    videoEnd: 18,
    holdVideo: true,
    overlays: [
      {
        id: 'highlight-point-3',
        type: 'highlight',
        startTime: 15,
        endTime: 18,
        target: { x: 0.565, y: 0.32, width: 0.02, height: 0.03 },
        label: 'Point 3: Y-Axis',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'origin-layout-step-6',
    title: '',
    customText: 'Origin Location Changed',
    narrationText: 'Origin Location Changed',
    videoStart: 21,
    videoEnd: 28,
    holdVideo: true,
    overlays: [
      {
        id: 'highlight-origin-changed',
        type: 'highlight',
        startTime: 21,
        endTime: 28,
        target: { x: 0.498, y: 0.606, width: 0.044, height: 0.094 },
        label: 'Origin Location Changed',
        labelPosition: 'bottom',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'origin-layout-quiz-1',
    title: 'Knowledge check',
    customText: 'What is the first action after selecting the Change 3D Part Layout tool?',
    videoStart: 20.83,
    videoEnd: 20.83,
    holdVideo: true,
    quizData: {
      question: 'What is the first action after selecting the Change 3D Part Layout tool?',
      options: [
        {
          text: "Right-click to display the model's current origin location",
          isCorrect: true,
          feedback: 'Correct! Right-clicking displays the current origin so you can establish reference before relocating it.',
        },
        {
          text: 'Left-click immediately to define Point 1',
          isCorrect: false,
          feedback: 'You must first right-click to inspect the current origin position.',
        },
        {
          text: 'Enter new coordinates in the Key Entry Area',
          isCorrect: false,
          feedback: 'Change 3D Part Layout uses model point clicks rather than keyboard coordinate entry.',
        },
      ],
    },
  },
  {
    id: 'origin-layout-quiz-2',
    title: 'Knowledge check',
    customText: 'In the 3-point origin layout method, which axis is defined by Point 2?',
    videoStart: 20.83,
    videoEnd: 20.83,
    holdVideo: true,
    quizData: {
      question: 'In the 3-point origin layout method, which axis is defined by Point 2?',
      options: [
        {
          text: 'The positive X-axis direction from the new origin',
          isCorrect: true,
          feedback: 'Correct! Point 1 is the new origin, Point 2 defines the X-axis direction, and Point 3 defines the Y-axis.',
        },
        {
          text: 'The vertical Z-axis depth',
          isCorrect: false,
          feedback: 'Point 2 defines the X-axis direction, not the Z-axis.',
        },
        {
          text: 'The center of rotation for the work plane',
          isCorrect: false,
          feedback: 'Point 2 sets the positive direction of the X-axis from Point 1.',
        },
      ],
    },
  },
  {
    id: 'origin-layout-quiz-3',
    title: 'Knowledge check',
    customText: 'What viewing plane is established after selecting Point 3 (Y-axis)?',
    videoStart: 20.83,
    videoEnd: 20.83,
    holdVideo: true,
    quizData: {
      question: 'What viewing plane is established after selecting Point 3 (Y-axis)?',
      options: [
        {
          text: 'The Front View (XY-plane)',
          isCorrect: true,
          feedback: 'Correct! In iCAD, the plane established by the origin, X-axis, and Y-axis becomes the Front View.',
        },
        {
          text: 'The Top View (XZ-plane)',
          isCorrect: false,
          feedback: 'The XY-plane established by Point 1, 2, and 3 forms the Front View, not the Top View.',
        },
        {
          text: 'The Side View (YZ-plane)',
          isCorrect: false,
          feedback: 'The XY-plane corresponds to the Front View, not the Side View.',
        },
      ],
    },
  },
  {
    id: 'origin-layout-recap',
    title: 'Change 3D Part Layout Recap',
    customText: 'Review the key steps for changing the 3D part layout and origin.',
    videoStart: 20.83,
    videoEnd: 20.83,
    holdVideo: true,
    recapData: {
      title: 'Change 3D Part Layout Recap',
      items: [
        'Select パーツ (3D PARTS ) → パーツのレイアウトを変更する from the icon menu.',
        'Right-click to show the current origin location on the model.',
        'Left-click Point 1 to establish the new origin position.',
        'Left-click Point 2 to set the X-axis direction.',
        'Left-click Point 3 to set the Y-axis and determine the Front View.',
      ],
    },
  },
];

export default ORIGIN_AXES_VIDEO_STEPS;
