import { LessonVideoStep } from './types';

export const SELECTING_GEOMETRY_VIDEO_STEPS: LessonVideoStep[] = [
  {
    id: 'select-geo-step-1',
    title: '1. Select Move Tool',
    customText: 'From the right menu, select 移動 (Move) under 移動・コピー・削除.',
    narrationText: 'From the right menu, select Move under Move, Copy, Delete.',
    narrateTitle: false,
    videoStart: 0,
    videoEnd: 3.2,
    overlays: [
      {
        id: 'highlight-move-group',
        type: 'highlight',
        startTime: 0.5,
        endTime: 3.0,
        target: { x: 0.902, y: 0.250, width: 0.070, height: 0.025 },
        label: 'Move / Copy / Delete',
        labelPosition: 'left',
        animation: 'pulse',
      },
      {
        id: 'highlight-move-icon',
        type: 'highlight',
        startTime: 1.0,
        endTime: 3.2,
        target: { x: 0.901, y: 0.264, width: 0.078, height: 0.069 },
        label: 'Move Tool',
        labelPosition: 'left',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'select-geo-step-2',
    title: '2. Check Prompt & Highlight',
    customText: 'Look at the prompt: 対象要素 (Target Element). Hover over the 3D block to see the yellow outline highlight.',
    narrationText: 'Look at the prompt bar asking for the target element. Move your cursor over the 3D block and observe the yellow outline highlight.',
    narrateTitle: false,
    videoStart: 3.2,
    videoEnd: 6.5,
    overlays: [
      {
        id: 'highlight-prompt-target',
        type: 'highlight',
        startTime: 3.2,
        endTime: 6.5,
        target: { x: 0.005, y: 0.970, width: 0.250, height: 0.025 },
        label: 'Prompt: Target Element GO',
        labelPosition: 'top',
        animation: 'pulse',
      },
      {
        id: 'highlight-box-selection',
        type: 'highlight',
        startTime: 3.8,
        endTime: 6.5,
        target: { x: 0.395, y: 0.441, width: 0.205, height: 0.304 },
        label: 'Yellow Outline Highlight',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'select-geo-step-3',
    title: '3. Left-Click to Select & Confirm with GO',
    customText: 'Left-click the object to select it, then click GO to confirm your selection.',
    narrationText: 'Left-click the object to select it, then click GO or press Enter to confirm your selection.',
    narrateTitle: false,
    videoStart: 6.5,
    videoEnd: 14.0,
    overlays: [
      {
        id: 'highlight-confirm-go',
        type: 'highlight',
        startTime: 6.5,
        endTime: 10.0,
        target: { x: 0.005, y: 0.970, width: 0.250, height: 0.025 },
        label: 'Confirm with GO',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'select-geo-quiz-1',
    title: 'Knowledge Check: Geometry Selection',
    customText: 'How do you know an object will be selected before you click it in iCAD SX?',
    videoStart: 13.9,
    videoEnd: 13.9,
    holdVideo: true,
    quizData: {
      question: 'How do you know an object will be selected before you click it in iCAD SX?',
      options: [
        {
          text: 'The object outline highlights in yellow when hovered',
          isCorrect: true,
          feedback: 'Correct! The yellow boundary highlight confirms the active target before clicking.',
        },
        {
          text: 'The object disappears from the workspace',
          isCorrect: false,
          feedback: 'Incorrect. The object stays visible with a yellow highlight.',
        },
        {
          text: 'The origin resets to zero',
          isCorrect: false,
          feedback: 'Incorrect. The origin is unchanged during geometry selection.',
        },
      ],
    },
  },
  {
    id: 'select-geo-step-4',
    title: '4. Enter Movement Distance',
    customText: 'In the bottom item entry area, enter the movement distance (X, Y, Z) and press Enter.',
    narrationText: 'In the bottom item entry area, enter the movement distance on the X, Y, and Z axes and press Enter.',
    narrateTitle: false,
    videoStart: 14.0,
    videoEnd: 24.0,
    overlays: [
      {
        id: 'highlight-movement-entry',
        type: 'highlight',
        startTime: 14.0,
        endTime: 20.0,
        target: { x: 0.005, y: 0.940, width: 0.300, height: 0.035 },
        label: 'Movement Entry: X, Y, Z',
        labelPosition: 'top',
        animation: 'pulse',
      },
    ],
  },
  {
    id: 'select-geo-step-5',
    title: '5. Verify Movement',
    customText: 'The selected object moves to its new position while other elements remain in place.',
    narrationText: 'The selected object moves to its new position while other elements remain in place.',
    narrateTitle: false,
    videoStart: 24.0,
    videoEnd: 36.78,
  },
  {
    id: 'select-geo-recap',
    title: 'Selecting Geometry Recap',
    customText: 'Review the key steps for selecting geometry in iCAD SX.',
    videoStart: 36.78,
    videoEnd: 36.78,
    holdVideo: true,
    recapData: {
      title: 'Selecting Geometry (Move Component) Recap',
      items: [
        'Select the operation tool (e.g. Move) from the menu.',
        'Check the guidance prompt: 対象要素 (Target Element).',
        'Hover over the object and verify the yellow highlight.',
        'Left-click to select the object.',
        'Click GO (or press Enter) to finish selecting.',
        'Enter movement values to complete the operation.',
      ],
    },
  },
];

export default SELECTING_GEOMETRY_VIDEO_STEPS;
